"""Generated by `hpc-agent interview` from intent.task_generator.

Re-running the interview with the same intent regenerates this file
byte-equivalently. To diverge from the recipe, drop `task_generator`
from the next intent.json — subsequent runs will accept the file you
hand-edit.
"""
from __future__ import annotations

_INJECT = {'imp_sentiment_sha': 'de8016ab735fa8d8', 'imp_implied_vol_sha': '201af89c82f7010a', 'imp_vol_demand_sha': 'c0e1462901274b01'}
_TASKS = [{'config': 'configs/imp_sentiment.yaml'}, {'config': 'configs/imp_implied_vol.yaml'}, {'config': 'configs/imp_vol_demand.yaml'}]

def total() -> int: return len(_TASKS)
def resolve(i: int) -> dict: return {**_TASKS[i], **_INJECT}
