"""Auto-generated by ``hpc-agent interview`` from intent.entry_point.

Do not edit by hand. The interview regenerates this file from the
declared argv + signature each time intent.entry_point changes. To
diverge from the wrapper pattern, drop ``entry_point`` from the next
intent.json and supply a hand-written ``@register_run`` notebook
instead.
"""
from __future__ import annotations

import subprocess
from hpc_agent.experiment_kit import register_run

@register_run
def har_base_sweep(ladder_arm: str, rungs_cap: int, chunk_start: int, chunk_end: int, halo: int, **kwargs) -> None:
    """Auto-generated shell-command wrapper. See module docstring."""
    subprocess.check_call(['env', f'LADDER_ARM={ladder_arm}', f'RUNGS_CAP={rungs_cap}', f'START={chunk_start}', f'END={chunk_end}', f'HALO={halo}', 'python3', 'specs/har_base_sweep.py'])
