"""Auto-generated by ``hpc-agent interview`` from intent.entry_point.

Do not edit by hand. The interview regenerates this file from the
declared argv + signature each time intent.entry_point changes. To
diverge from the wrapper pattern, drop ``entry_point`` from the next
intent.json and supply a hand-written ``@register_run`` notebook
instead.
"""
from __future__ import annotations

import subprocess
from hpc_agent.experiment_kit import register_run

@register_run
def ridge_sweep(config: str, **kwargs) -> None:
    """Auto-generated shell-command wrapper. See module docstring."""
    subprocess.check_call(['python', 'run.py', '--config', str(config)])
