"""Render the deck's buy-signal reading (§16) as a booktabs table and a standalone PDF source.

Reads results/atm_straddle_0dte_1530/buy_signal_reading.csv (written by the deck) and the
block-diagonal ridge's per-day file for the base rates (the same statistics over all 866 days
with the package held every day, no forecast), and writes

  writeup/generated/table_buy_signal.tex   the tabular (two panels: buy days, sell days)
  writeup/buy_signal_standalone.tex        the standalone document (table + figure)

Build: pdflatex -interaction=nonstopmode buy_signal_standalone.tex
"""

from __future__ import annotations

import os

import numpy as np
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "results", "atm_straddle_0dte_1530")
GEN = os.path.join(ROOT, "writeup", "generated")

MODEL_TEX = {
    "baseline (HAR + calendar OLS)": r"baseline (HAR + calendar OLS)",
    "block-diagonal ridge": r"block-diagonal ridge",
    "block-diagonal ridge, without the FOMC columns": r"block-diagonal ridge, no FOMC columns",
    "LightGBM": r"LightGBM",
    "XGBoost": r"XGBoost",
    "lasso (causally tuned)": r"lasso (causally tuned)",
    "lasso (fixed 1e-4)": r"lasso ($\alpha=10^{-4}$)",
    "elastic net (causally tuned)": r"elastic net (causally tuned)",
}
COLS = [
    ("n", "{:.0f}", r"$n$"),
    ("hit rate", "{:.3f}", r"hit rate"),
    ("avg win", "{:+.3f}", r"avg.\ win"),
    ("avg loss", "{:+.3f}", r"avg.\ loss"),
    ("mean per active day", "{:+.3f}", r"mean/day"),
    ("share R = -1", "{:.3f}", r"$P(R=-1)$"),
]


def side_stats(x: pd.Series, r: pd.Series) -> dict[str, float]:
    # x is the position's return (R long, -R short); the worthless share is on R itself
    x = x.to_numpy(dtype=float)
    return {
        "n": float(len(x)),
        "hit rate": float((x > 0).mean()),
        "avg win": float(x[x > 0].mean()),
        "avg loss": float(x[x <= 0].mean()),
        "mean per active day": float(x.mean()),
        "share R = -1": float(np.isclose(r.to_numpy(dtype=float), -1.0).mean()),
    }


def render() -> list[str]:
    tab = pd.read_csv(os.path.join(SRC, "buy_signal_reading.csv"))
    r = pd.read_parquet(os.path.join(SRC, "daily_blk2.parquet"))["R"]
    base = {"buy (s > 0)": side_stats(r, r), "sell (s <= 0)": side_stats(-r, r)}
    base_label = {
        "buy (s > 0)": r"\emph{base rate: long the package every day}",
        "sell (s <= 0)": r"\emph{base rate: short the package every day}",
    }
    ncol = len(COLS) + 1
    lines = [
        "% AUTO-GENERATED by writeup/make_buy_signal_tex.py -- do not edit.",
        "% Source: results/atm_straddle_0dte_1530/buy_signal_reading.csv and daily_blk2.parquet",
        r"\begingroup\small\setlength{\tabcolsep}{5pt}",
        r"\begin{tabular}{l" + "r" * len(COLS) + "}",
        r"\toprule",
        "& " + " & ".join(h for _, _, h in COLS) + r" \\",
    ]
    for side, title in (
        ("buy (s > 0)", r"Buy days ($s_t>0$): the long package's return $R$"),
        ("sell (s <= 0)", r"Sell days ($s_t\le 0$): the short package's return $-R$"),
    ):
        lines.append(r"\midrule")
        lines.append(r"\multicolumn{%d}{l}{\emph{%s}} \\" % (ncol, title))
        for _, row in tab[tab["side"] == side].iterrows():
            cells = [MODEL_TEX.get(str(row["forecast"]), str(row["forecast"]))]
            for col, fmt, _ in COLS:
                cells.append(fmt.format(float(row[col])))
            lines.append(" & ".join(cells) + r" \\")
        cells = [base_label[side]]
        for col, fmt, _ in COLS:
            cells.append(fmt.format(base[side][col]))
        lines.append(" & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\endgroup", ""]
    return lines


STANDALONE = r"""% Standalone render of generated/table_buy_signal.tex
% Build: pdflatex -interaction=nonstopmode buy_signal_standalone.tex
\documentclass{article}
\usepackage[landscape,margin=0.4in]{geometry}
\usepackage{booktabs}
\usepackage{amsmath}
\usepackage{graphicx}
\pagestyle{empty}
\begin{document}
\begin{center}
\textbf{0DTE 15:30--16:00 nearest-OTM package: how often the signal is right, and by how much, 866 common days}\\[1.5ex]
\input{generated/table_buy_signal}
\end{center}
\vspace{1ex}
\begin{center}
\includegraphics[width=0.78\textwidth]{../results/atm_straddle_0dte_1530/buy_signal_hitrate.png}
\end{center}
\vspace{1ex}
\noindent\small A hit on a buy day is $R>0$; on a sell day it is $R<0$. The average win and loss are the
conditional means of the position's return, $R$ on buy days and $-R$ on sell days, on its winning and
losing days; mean/day is the position's mean return per active day; $P(R=-1)$ is the share of days the
package expires worthless. The base-rate rows are the same statistics over all 866 days with the package
held every day and no forecast: long for the buy panel, short for the sell panel. Mid fill; returns in
units of the entry premium. In the figure, bars are the signal's days and the dashed lines are the base rates.
\end{document}
"""


def main() -> None:
    os.makedirs(GEN, exist_ok=True)
    with open(
        os.path.join(GEN, "table_buy_signal.tex"), "w", encoding="utf-8", newline="\n"
    ) as fh:
        fh.write("\n".join(render()))
    with open(
        os.path.join(ROOT, "writeup", "buy_signal_standalone.tex"),
        "w",
        encoding="utf-8",
        newline="\n",
    ) as fh:
        fh.write(STANDALONE)
    print(
        "wrote",
        os.path.join(GEN, "table_buy_signal.tex"),
        "and writeup/buy_signal_standalone.tex",
    )


if __name__ == "__main__":
    main()
