"""Render results/atm_straddle_0dte_1530/rule_*.csv as booktabs tables.

Two tables, each with a wide (all columns) and a narrow ("paper") variant:

  table_rule_by_strategy.tex        one panel per portfolio rule, models down the rows
  table_rule_by_strategy_paper.tex  same, reduced column set for the portrait paper
  table_rule_flat_fomc_me.tex       unit-median VRP flat on FOMC + month-end,
                                    full sample / daily-0DTE era panels
  table_rule_flat_fomc_me_paper.tex same, reduced column set

Reads the CSVs the notebook wrote (never retypes a number) and writes
self-contained tabulars, to be wrapped in a table float at the include site.
"""

from __future__ import annotations

import os

import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "results", "atm_straddle_0dte_1530")
GEN = os.path.join(ROOT, "writeup", "generated")

# (csv stem, panel label) in display order
PANELS = [
    ("rule_by_strategy_always_short", r"Short volatility (always short)"),
    (
        "rule_by_strategy_long_short_volatility",
        r"Long--short volatility ($\pm 1$ on $\mathrm{sign}(s)$)",
    ),
    ("rule_by_strategy_unit_median_VRP", r"Unit-median VRP size"),
]

FLAT_PANELS = [
    (
        "rule_flat_fomc_me_full",
        r"Full sample (2020--2024-04): 83 of 871 days flat",
    ),
    (
        "rule_flat_fomc_me_era",
        r"Daily-0DTE era (2022-05-16+): 38 of 492 days flat",
    ),
]

MODEL_TEX = {
    "HAR + calendar OLS": r"HAR + calendar OLS",
    "HAR+calendar OLS": r"HAR + calendar OLS",
    "two-block ridge": r"block-diag ridge",
    "two-block ridge (FOMC in X)": r"block-diag ridge",
    "gen. Tikhonov ridge": r"block-diag ridge",
    "block-diag ridge": r"block-diag ridge",
    "LightGBM": r"LightGBM",
    "XGBoost": r"XGBoost",
    "LGBM all-features": r"LightGBM",
    "XGB all-features": r"XGBoost",
    "lasso (tuned)": r"lasso (causally tuned)",
    "lasso (causally tuned)": r"lasso (causally tuned)",
    "lasso (fixed 1e-4)": r"lasso ($\alpha=10^{-4}$)",
    "lasso all-features (tuned)": r"lasso (causally tuned)",
    "lasso all-features (fixed 1e-4)": r"lasso ($\alpha=10^{-4}$)",
    "all models": r"all models (no forecast)",
    "elastic net (causally tuned)": r"elastic net (causally tuned)",
    "elastic net": r"elastic net (causally tuned)",
}

# (csv column, format, tex header cell) — display order.
COLS = [
    ("n", "{:.0f}", r"$n$"),
    ("mean", "{:.3f}", r"mean"),
    ("std", "{:.3f}", r"std"),
    ("min", "{:.2f}", r"min"),
    ("25%", "{:.3f}", r"25\%"),
    ("50%", "{:.3f}", r"50\%"),
    ("75%", "{:.3f}", r"75\%"),
    ("max", "{:.2f}", r"max"),
    ("skew", "{:.2f}", r"skew"),
    ("ex_kurt", "{:.2f}", r"ex.\ kurt"),
    ("t_mean", "{:.2f}", r"$t$"),
    ("Sharpe_ann", "{:.2f}", r"Sharpe$_{\mathrm{ann}}$"),
    ("n_buy", "{:.0f}", r"$n_{\mathrm{buy}}$"),
    ("pct_buy", "{:.1f}", r"\%buy"),
]

# Narrow variant for the portrait-width paper: drop the quartiles and the
# net-long counts.
PAPER_DROP = {"25%", "50%", "75%", "n_buy", "pct_buy"}
PAPER_COLS = [c for c in COLS if c[0] not in PAPER_DROP]


def render(panels, cols, sources: str, tabcolsep: str) -> list[str]:
    """One tabular: `panels` is a list of (csv stem, panel label)."""
    ncol = len(cols) + 1
    header = "& " + " & ".join(h for _, _, h in cols) + r" \\"
    lines = [
        "% AUTO-GENERATED by writeup/make_rule_by_strategy_tex.py — do not edit.",
        f"% Source: {sources}",
        r"\begingroup\small\setlength{\tabcolsep}{%s}" % tabcolsep,
        r"\begin{tabular}{l" + "r" * len(cols) + "}",
        r"\toprule",
        header,
    ]
    for stem, label in panels:
        df = pd.read_csv(os.path.join(SRC, f"{stem}.csv"), index_col=0)
        lines.append(r"\midrule")
        lines.append(r"\multicolumn{%d}{l}{\emph{%s}} \\" % (ncol, label))
        for name, row in df.iterrows():
            cells = [MODEL_TEX.get(str(name), str(name))]
            for col, fmt, _ in cols:
                cells.append(fmt.format(float(row[col])))
            lines.append(" & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\endgroup", ""]
    return lines


def write(name: str, lines: list[str]) -> None:
    dst = os.path.join(GEN, name)
    os.makedirs(GEN, exist_ok=True)
    with open(dst, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))
    print("wrote", dst)


def main() -> None:
    by_strategy_src = "results/atm_straddle_0dte_1530/rule_by_strategy_*.csv"
    flat_src = "results/atm_straddle_0dte_1530/rule_flat_fomc_me_{full,era}.csv"
    write(
        "table_rule_by_strategy.tex",
        render(PANELS, COLS, by_strategy_src, "3.5pt"),
    )
    write(
        "table_rule_by_strategy_paper.tex",
        render(PANELS, PAPER_COLS, by_strategy_src, "4.5pt"),
    )
    flat_ok = all(
        os.path.exists(os.path.join(SRC, f"{stem}.csv")) for stem, _ in FLAT_PANELS
    )
    if flat_ok:
        write(
            "table_rule_flat_fomc_me.tex",
            render(FLAT_PANELS, COLS, flat_src, "3.5pt"),
        )
        write(
            "table_rule_flat_fomc_me_paper.tex",
            render(FLAT_PANELS, PAPER_COLS, flat_src, "4.5pt"),
        )
    else:
        print("skip flat FOMC/ME tables (CSV missing)")


if __name__ == "__main__":
    main()
