"""Build the running appendix's tables and prose numbers from executed outputs.

The running appendix (writeup/sections/appendix_running.tex) collects the side
analyses that sit outside the paper's main line.  This script writes

  writeup/generated/appendix_running_<item>.tex   one booktabs tabular per table
  writeup/generated/appendix_running_numbers.tex  \\newcommand macros (\\runapp...)
                                                  for every number quoted in prose

and nothing else.  Every number is read from a committed results CSV, a study's
saved summary, or an executed notebook's saved output text; nothing is typed in
by hand.  Each generated file names its source in a comment.  A few gates assert
that two outputs of the same quantity agree before either is used.

The one optional input is the direct rest-of-day trading test, which another
workstream writes to results/linear_subsection_restofday/trading_test/.  When a
``summary.csv`` lands there this script renders it as
appendix_running_restofday_trade.tex (the section inputs it under
\\IfFileExists); until then that file is not written.

Run:  python writeup/make_appendix_running_tex.py
"""

from __future__ import annotations

import json
import math
import re
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
GEN = ROOT / "writeup" / "generated"
RES = ROOT / "results"
HC = RES / "atm_straddle_intraday_holdclose"  # delta-hedged hold-to-close
RP = RES / "atm_straddle_intraday"  # 30-minute re-pick
CL = RES / "atm_straddle_0dte_1530"  # the 15:30 close trade (rv_iv notebook)
PROP = HC / "proposals"
NB_RVIV = ROOT / "notebooks" / "atm_straddle_rv_iv.executed.ipynb"
NB_HC = ROOT / "notebooks" / "atm_straddle_intraday_holdclose.executed.ipynb"
NB_RP = ROOT / "notebooks" / "atm_straddle_intraday.executed.ipynb"

CLOCKS_DH = [
    "0935",
    "1000",
    "1030",
    "1100",
    "1130",
    "1200",
    "1230",
    "1300",
    "1330",
    "1400",
    "1430",
    "1500",
    "1530",
]
RIDGE = "block-diagonal ridge"
# Two outputs of the same number agree to rounding at this tolerance.
TOL = 1e-6
# Significance level of the per-clock Diebold--Mariano tests the scorer reports.
ALPHA = 0.05

NUMS: dict[str, str] = {}
WRITTEN: list[str] = []  # the tables this run wrote


# --------------------------------------------------------------------------- formatting
def fnum(x: float, d: int = 2, plus: bool = False) -> str:
    """A number for LaTeX text or math: true minus sign, optional explicit plus."""
    if x is None or (isinstance(x, float) and not math.isfinite(x)):
        return "---"
    s = f"{abs(float(x)):.{d}f}"
    if float(x) < 0 and float(s) != 0.0:
        return r"\ensuremath{-}" + s
    if plus and float(s) != 0.0:
        return r"\ensuremath{+}" + s
    return s


def fci(lo: float, hi: float, d: int = 2) -> str:
    return f"[{fnum(lo, d)}, {fnum(hi, d)}]"


def fint(x: float) -> str:
    return f"{int(round(float(x))):,}".replace(",", "{,}")


def macro(name: str, value: str) -> None:
    assert re.fullmatch(r"[A-Za-z]+", name), name
    assert name not in NUMS, f"macro defined twice: {name}"
    NUMS[name] = value


def tex_escape(s: str) -> str:
    return (
        s.replace("\\", r"\textbackslash{}")
        .replace("&", r"\&")
        .replace("%", r"\%")
        .replace("_", r"\_")
        .replace("#", r"\#")
    )


def stack(cell: str) -> str:
    """A header cell whose ``~~`` marks line breaks, as a shortstack.

    A line that opens with ``[`` is guarded with ``{}`` so that the line break
    before it does not read it as its optional argument.
    """
    if "~~" not in cell:
        return cell
    parts = [("{}" + x) if x.startswith("[") else x for x in cell.split("~~")]
    return r"\shortstack{" + r"\\".join(parts) + "}"


def write_tab(
    name: str, sources: list[str], colspec: str, header: list[str], body: list[str]
) -> None:
    """One booktabs tabular; ``body`` lines are complete rows or rules."""
    header = [stack(h) for h in header]
    lines = [
        "% AUTO-GENERATED by writeup/make_appendix_running_tex.py -- do not edit.",
        *[f"% Source: {s}" for s in sources],
        r"\begin{tabular}{" + colspec + "}",
        r"\toprule",
        " & ".join(header) + r" \\",
        r"\midrule",
        *body,
        r"\bottomrule",
        r"\end{tabular}",
    ]
    (GEN / f"appendix_running_{name}.tex").write_text(
        "\n".join(lines) + "\n", encoding="utf-8", newline="\n"
    )
    WRITTEN.append(name)


def row(cells: list[str]) -> str:
    return " & ".join(cells) + r" \\"


def panel(title: str, ncol: int) -> str:
    return r"\multicolumn{" + str(ncol) + r"}{l}{\emph{" + title + r"}} \\"


# --------------------------------------------------------------------------- notebooks
def nb_output(path: Path, marker: str) -> str:
    """All saved text output of the first cell whose output contains ``marker``."""
    nb = json.loads(path.read_text(encoding="utf-8"))
    for cell in nb["cells"]:
        parts = []
        for out in cell.get("outputs", []):
            txt = "".join(out.get("text", "")) if "text" in out else ""
            if not txt and "data" in out:
                txt = "".join(out["data"].get("text/plain", ""))
            parts.append(txt)
        joined = "\n".join(parts)
        if marker in joined:
            return joined
    raise KeyError(f"{path.name}: no saved output contains {marker!r}")


FLOAT = r"[-+]?\d+(?:\.\d+)?"


# =========================================================================== item 1
def repick() -> None:
    """The 30-minute re-pick (unhedged): pooled rules and the eight forecasts."""
    src_a = RP / "rule_table_intraday_blk2.csv"
    src_x = RP / "rule_table_intraday_crossed_blk2.csv"
    a = pd.read_csv(src_a).set_index("rule")
    x = pd.read_csv(src_x).set_index("rule")
    assert (a.index == x.index).all()
    for r in a.index:  # the two files carry the same midpoint Sharpe
        assert abs(a.loc[r, "Sharpe_ann"] - x.loc[r, "Sharpe mid"]) < TOL, r
    labels = {
        "always short": "always short",
        "always short, flat at 15:30": "always short, flat at 15:30",
        "sign(s)": r"$\mathrm{sign}(s^{\mathrm m})$",
        "always short, sign(s) close": r"always short, $\mathrm{sign}(s^{\mathrm m})$ at 15:30",
    }
    body = [panel(r"(a) four rules, block-diagonal ridge", 8)]
    for r, lab in labels.items():
        body.append(
            row(
                [
                    lab,
                    fnum(a.loc[r, "mean_daily"], 3),
                    fnum(a.loc[r, "t_mean"], 2),
                    fnum(a.loc[r, "Sharpe_ann"], 2),
                    fnum(x.loc[r, "Sharpe crossed-spread"], 2),
                    fnum(x.loc[r, "crossings/day"], 1),
                    fnum(x.loc[r, "break-even half-spread % prem"], 2),
                    fnum(a.loc[r, "pct_buy"], 1),
                ]
            )
        )
    # (b) the eight forecasts, censored implied re-inverted as in the main text
    pdir = RP / "rule_by_strategy" / "pooled"
    s = pd.read_csv(pdir / "rule_by_strategy_sign_s.csv", index_col=0)
    sh = pd.read_csv(pdir / "rule_by_strategy_always_short.csv", index_col=0)
    assert abs(sh["Sharpe_ann"].iloc[0] - a.loc["always short", "Sharpe_ann"]) < TOL
    body.append(r"\midrule")
    body.append(panel(r"(b) $\mathrm{sign}(s^{\mathrm m})$ for each forecast", 8))
    for f, r in s.iterrows():
        body.append(
            row(
                [
                    tex_escape(str(f)).replace("fixed 1e-4", r"$\alpha=10^{-4}$"),
                    fnum(r["mean"], 3),
                    fnum(r["t_mean"], 2),
                    fnum(r["Sharpe_ann"], 2),
                    fnum(r["Sharpe_crossed"], 2),
                    "---",
                    "---",
                    "---",
                ]
            )
        )
    write_tab(
        "repick",
        [
            src_a.relative_to(ROOT).as_posix(),
            src_x.relative_to(ROOT).as_posix(),
            (pdir / "rule_by_strategy_sign_s.csv").relative_to(ROOT).as_posix(),
        ],
        "lrrrrrrr",
        [
            "",
            "mean/day",
            "$t$",
            "Sharpe~~(mid)",
            "Sharpe~~(crossed)",
            "crossings~~per day",
            r"break-even half-~~spread (\% prem.)",
            r"\% bars~~bought",
        ],
        body,
    )
    macro("runappRpNdays", fint(a["n_days"].iloc[0]))
    macro("runappRpAsMid", fnum(a.loc["always short", "Sharpe_ann"]))
    macro("runappRpAsX", fnum(x.loc["always short", "Sharpe crossed-spread"]))
    macro("runappRpFlatMid", fnum(a.loc["always short, flat at 15:30", "Sharpe_ann"]))
    macro(
        "runappRpFlatX",
        fnum(x.loc["always short, flat at 15:30", "Sharpe crossed-spread"]),
    )
    macro("runappRpSignMid", fnum(a.loc["sign(s)", "Sharpe_ann"]))
    macro("runappRpSignX", fnum(x.loc["sign(s)", "Sharpe crossed-spread"]))
    macro("runappRpHybMid", fnum(a.loc["always short, sign(s) close", "Sharpe_ann"]))
    macro(
        "runappRpHybX",
        fnum(x.loc["always short, sign(s) close", "Sharpe crossed-spread"]),
    )
    assert (x["Sharpe crossed-spread"] < 0).all(), (
        "every re-pick rule is negative at the crossed spread"
    )
    # the prose: the hybrid is the least negative crossed rule; sign(s) beats always short at the mid
    assert x["Sharpe crossed-spread"].idxmax() == "always short, sign(s) close"
    assert a.loc["sign(s)", "Sharpe_ann"] > a.loc["always short", "Sharpe_ann"]
    macro("runappRpXMin", fnum(x["Sharpe crossed-spread"].min()))
    macro("runappRpXMax", fnum(x["Sharpe crossed-spread"].max()))
    macro("runappRpMidMin", fnum(a["Sharpe_ann"].min()))
    macro("runappRpMidMax", fnum(a["Sharpe_ann"].max()))
    macro("runappRpXingLo", fnum(x["crossings/day"].min(), 1))
    macro("runappRpXingHi", fnum(x["crossings/day"].max(), 1))
    macro("runappRpBeLo", fnum(x["break-even half-spread % prem"].min()))
    macro("runappRpBeHi", fnum(x["break-even half-spread % prem"].max()))
    txt = nb_output(NB_RP, "median half-spread")
    m = re.search(
        r"median half-spread ([\d.]+) pts = ([\d.]+)% of midpoint premium", txt
    )
    assert m, "re-pick half-spread line"
    macro("runappRpHalfSpread", m.group(2))
    # the prose: the median half-spread is above every rule's break-even half-spread
    assert float(m.group(2)) > x["break-even half-spread % prem"].max()
    m = re.search(r"are the (\d+) with a censored vendor implied volatility", txt)
    assert m, "re-pick censored-bar count"
    macro("runappRpCensored", m.group(1))
    assert float(m.group(1)) > 0
    macro("runappRpEightMidLo", fnum(s["Sharpe_ann"].min()))
    macro("runappRpEightMidHi", fnum(s["Sharpe_ann"].max()))
    macro("runappRpEightXLo", fnum(s["Sharpe_crossed"].min()))
    macro("runappRpEightXHi", fnum(s["Sharpe_crossed"].max()))
    macro("runappRpRidgeReinv", fnum(s.loc[RIDGE, "Sharpe_ann"]))


# =========================================================================== item 2
def holdclose() -> None:
    """Delta-hedged hold-to-close: pooled rules, confusion matrices, fitted rest-of-day maps."""
    src_a = HC / "rule_table_intraday_blk2.csv"
    src_x = HC / "rule_table_intraday_crossed_blk2.csv"
    a = pd.read_csv(src_a).set_index("rule")
    x = pd.read_csv(src_x).set_index("rule")
    for r in a.index:
        assert abs(a.loc[r, "Sharpe_ann"] - x.loc[r, "Sharpe mid"]) < TOL, r
    labels = {"always short": "always short", "sign(s)": r"$\mathrm{sign}(s)$"}
    body = []
    for r, lab in labels.items():
        body.append(
            row(
                [
                    lab,
                    fint(a.loc[r, "n_days"]),
                    fnum(a.loc[r, "mean_daily"], 3),
                    fnum(a.loc[r, "t_mean"], 2),
                    fnum(a.loc[r, "Sharpe_ann"], 2),
                    fnum(x.loc[r, "Sharpe crossed-spread"], 2),
                    fnum(x.loc[r, "mean/day crossed-spread"], 3),
                    fnum(x.loc[r, "settlement leg Sharpe crossed-spread"], 2),
                    fnum(a.loc[r, "pct_buy"], 1),
                ]
            )
        )
    write_tab(
        "holdclose",
        [src_a.relative_to(ROOT).as_posix(), src_x.relative_to(ROOT).as_posix()],
        "lrrrrrrrr",
        [
            "",
            "days",
            "mean/day",
            "$t$",
            "Sharpe~~(mid)",
            "Sharpe~~(crossed)",
            "mean/day~~(crossed)",
            "15:30 leg Sharpe~~(crossed)",
            r"\% bars~~bought",
        ],
        body,
    )
    # the prose: the forecast-free control is ahead of sign(s) at both fills, pooled
    assert a.loc["always short", "Sharpe_ann"] > a.loc["sign(s)", "Sharpe_ann"]
    assert (
        x.loc["always short", "Sharpe crossed-spread"]
        > x.loc["sign(s)", "Sharpe crossed-spread"]
        > 0
    )
    macro("runappHcNdays", fint(a["n_days"].iloc[0]))
    macro("runappHcNbars", fint(a["n"].iloc[0]))
    macro("runappHcAsMid", fnum(a.loc["always short", "Sharpe_ann"]))
    macro("runappHcSignMid", fnum(a.loc["sign(s)", "Sharpe_ann"]))
    macro("runappHcAsX", fnum(x.loc["always short", "Sharpe crossed-spread"]))
    macro("runappHcSignX", fnum(x.loc["sign(s)", "Sharpe crossed-spread"]))
    macro("runappHcSignPctBuy", fnum(a.loc["sign(s)", "pct_buy"], 1))
    macro(
        "runappHcAsLegX",
        fnum(x.loc["always short", "settlement leg Sharpe crossed-spread"]),
    )
    macro(
        "runappHcSignLegX",
        fnum(x.loc["sign(s)", "settlement leg Sharpe crossed-spread"]),
    )

    # ---- confusion matrices by clock (holdclose notebook section 8c)
    src_c = HC / "confusion_matrix_by_clock.csv"
    c = pd.read_csv(src_c)
    c["short_acc"] = 1.0 - c["base rate P(R>0)"]
    body = []
    for _, r in c.iterrows():
        body.append(
            row(
                [
                    r["hhmm"],
                    fint(r["n"]),
                    fnum(r["accuracy"], 3),
                    fnum(r["short_acc"], 3),
                    fnum(r["buy share"], 3),
                    fnum(r["base rate P(R>0)"], 3),
                    fnum(r["P(R>0 | buy)"], 3),
                    fnum(r["P(R<=0 | sell)"], 3),
                ]
            )
        )
    write_tab(
        "confusion",
        [src_c.relative_to(ROOT).as_posix()],
        "lrrrrrrr",
        [
            "entry",
            "days",
            r"accuracy~~$\mathrm{sign}(s)$",
            "accuracy~~always short",
            "buy~~share",
            r"$P(R>0)$",
            r"$P(R>0\mid\text{buy})$",
            r"$P(R\le 0\mid\text{sell})$",
        ],
        body,
    )
    macro("runappCmAccLo", fnum(c["accuracy"].min()))
    macro("runappCmAccHi", fnum(c["accuracy"].max()))
    macro("runappCmShortLo", fnum(c["short_acc"].min()))
    macro("runappCmShortHi", fnum(c["short_acc"].max()))
    n_below = int((c["accuracy"] < c["short_acc"]).sum())
    macro("runappCmBelow", str(n_below))
    macro("runappCmClocks", str(len(c)))
    macro(
        "runappCmBuyBeats", str(int((c["P(R>0 | buy)"] > c["base rate P(R>0)"]).sum()))
    )
    macro(
        "runappCmSellBeats",
        str(int((c["P(R<=0 | sell)"] > 1 - c["base rate P(R>0)"]).sum())),
    )

    # ---- rest-of-day maps fitted on the rest of the day (section 8d)
    src_r = HC / "rule_table_srem_blk2.csv"
    src_d = HC / "srem_vs_sm_dsharpe.csv"
    r8 = pd.read_csv(src_r).set_index("rule")
    d8 = pd.read_csv(src_d)
    d8 = d8[d8["fill"] == "mid"].set_index("signal")
    dx = pd.read_csv(src_d)
    txt = nb_output(
        NB_HC, "QLIKE of the rest-of-day forecast against the realized rest of the day"
    )
    m = re.search(
        r"^pooled\s+("
        + FLOAT
        + r")\s+("
        + FLOAT
        + r")\s+("
        + FLOAT
        + r")\s+("
        + FLOAT
        + r")\s*$",
        txt,
        re.M,
    )
    assert m, "section 8d pooled QLIKE line"
    q = [float(g) for g in m.groups()]  # stretch, M1, M2, M3
    rows_8d = [
        ("always short", "always short (no forecast)", None, None),
        (
            "sign(s^m)",
            r"$\mathrm{sign}(s)$, profile stretch $\widehat{RV}_t/w_t$",
            q[0],
            None,
        ),
        ("sign(s^rem) M1", r"$\mathrm{sign}(s^{\mathrm{rem}})$, M1", q[1], "M1"),
        ("sign(s^rem) M2", r"$\mathrm{sign}(s^{\mathrm{rem}})$, M2", q[2], "M2"),
        ("sign(s^rem) M3", r"$\mathrm{sign}(s^{\mathrm{rem}})$, M3", q[3], "M3"),
    ]
    body = []
    for key, lab, ql, sig in rows_8d:
        rr = r8.loc[key]
        dis = fnum(d8.loc[sig, "disagree % of bars"], 1) if sig else "---"
        ds = fnum(d8.loc[sig, "dSharpe"], 2, plus=True) if sig else "---"
        dci = fci(d8.loc[sig, "pct lo"], d8.loc[sig, "pct hi"]) if sig else "---"
        body.append(
            row(
                [
                    lab,
                    fnum(ql, 4) if ql is not None else "---",
                    fnum(rr["Sharpe_ann"], 2),
                    fnum(rr["Sharpe crossed-spread"], 2),
                    fnum(rr["pct_buy"], 1),
                    dis,
                    ds,
                    dci,
                ]
            )
        )
    write_tab(
        "restofday_maps",
        [
            src_r.relative_to(ROOT).as_posix(),
            src_d.relative_to(ROOT).as_posix(),
            f"{NB_HC.relative_to(ROOT).as_posix()} (section 8d, pooled QLIKE line of the saved output)",
        ],
        "lrrrrrrr",
        [
            "",
            "QLIKE,~~rest of day",
            "Sharpe~~(mid)",
            "Sharpe~~(crossed)",
            r"\% bars~~bought",
            r"\% bars sign~~differs",
            r"$\Delta$Sharpe~~(mid)",
            r"95\%~~interval",
        ],
        body,
    )
    macro("runappMapNbars", fint(r8["n"].iloc[0]))
    macro("runappMapQStretch", fnum(q[0], 4))
    macro("runappMapQOne", fnum(q[1], 4))
    macro("runappMapQTwo", fnum(q[2], 4))
    macro("runappMapQThree", fnum(q[3], 4))
    macro("runappMapAsMid", fnum(r8.loc["always short", "Sharpe_ann"]))
    macro("runappMapAsX", fnum(r8.loc["always short", "Sharpe crossed-spread"]))
    macro("runappMapSmMid", fnum(r8.loc["sign(s^m)", "Sharpe_ann"]))
    macro("runappMapSmX", fnum(r8.loc["sign(s^m)", "Sharpe crossed-spread"]))
    for k, nm in (("M1", "One"), ("M2", "Two"), ("M3", "Three")):
        macro(f"runappMap{nm}Mid", fnum(r8.loc[f"sign(s^rem) {k}", "Sharpe_ann"]))
        macro(
            f"runappMap{nm}X", fnum(r8.loc[f"sign(s^rem) {k}", "Sharpe crossed-spread"])
        )
        macro(f"runappMap{nm}Dis", fnum(d8.loc[k, "disagree % of bars"], 1))
        macro(f"runappMap{nm}Buy", fnum(r8.loc[f"sign(s^rem) {k}", "pct_buy"], 1))
    macro("runappMapSmBuy", fnum(r8.loc["sign(s^m)", "pct_buy"], 1))
    macro("runappMapOneDs", fnum(d8.loc["M1", "dSharpe"]))
    macro("runappMapOneCi", fci(d8.loc["M1", "pct lo"], d8.loc["M1", "pct hi"]))
    n_ex = int((dx["pct hi"] < 0).sum())
    macro("runappMapExcl", str(n_ex))
    macro("runappMapIntervals", str(len(dx)))
    assert q[3] < q[0] < q[1] < q[2], "the ordering the prose states"


# =========================================================================== item 3
def perclock() -> None:
    """Sharpe ratio by entry clock: the re-pick and the delta-hedged hold-to-close."""
    rows_out = []
    for ck in CLOCKS_DH:
        hh = f"{ck[:2]}:{ck[2:]}"
        dh = HC / "rule_by_strategy_dh" / ck
        s = pd.read_csv(dh / "rule_by_strategy_sign_s.csv", index_col=0)
        a = pd.read_csv(dh / "rule_by_strategy_always_short.csv", index_col=0)
        rp = RP / "rule_by_strategy" / ck
        if rp.exists():
            rs = pd.read_csv(rp / "rule_by_strategy_sign_s.csv", index_col=0)
            ra = pd.read_csv(rp / "rule_by_strategy_always_short.csv", index_col=0)
            rp_as, rp_sg = (
                float(ra["Sharpe_ann"].iloc[0]),
                float(rs.loc[RIDGE, "Sharpe_ann"]),
            )
            rp_min, rp_max = (
                float(rs["Sharpe_ann"].min()),
                float(rs["Sharpe_ann"].max()),
            )
        else:
            rp_as = rp_sg = rp_min = rp_max = float("nan")
        rows_out.append(
            dict(
                clock=hh,
                n=int(a["n"].iloc[0]),
                rp_as=rp_as,
                rp_sg=rp_sg,
                rp_min=rp_min,
                rp_max=rp_max,
                as_mid=float(a["Sharpe_ann"].iloc[0]),
                as_x=float(a["Sharpe_crossed"].iloc[0]),
                sg_mid=float(s.loc[RIDGE, "Sharpe_ann"]),
                sg_x=float(s.loc[RIDGE, "Sharpe_crossed"]),
                sg_min=float(s["Sharpe_ann"].min()),
                sg_max=float(s["Sharpe_ann"].max()),
            )
        )
    t = pd.DataFrame(rows_out).set_index("clock")
    body = [
        row(
            [
                ck,
                fint(r["n"]),
                fnum(r["rp_as"]),
                fnum(r["rp_sg"]),
                fnum(r["as_mid"]),
                fnum(r["as_x"]),
                fnum(r["sg_mid"]),
                fnum(r["sg_x"]),
                (f"{fnum(r['sg_min'])} to {fnum(r['sg_max'])}"),
            ]
        )
        for ck, r in t.iterrows()
    ]
    write_tab(
        "perclock",
        [
            "results/atm_straddle_intraday/rule_by_strategy/<hhmm>/rule_by_strategy_{always_short,sign_s}.csv (30-minute re-pick)",
            "results/atm_straddle_intraday_holdclose/rule_by_strategy_dh/<hhmm>/rule_by_strategy_{always_short,sign_s}.csv (hold to close, delta-hedged)",
        ],
        "lrrrrrrrr",
        [
            "entry",
            "days",
            r"\shortstack{re-pick\\always short}",
            r"\shortstack{re-pick\\$\mathrm{sign}(s)$}",
            r"\shortstack{to close\\always short}",
            r"\shortstack{to close\\always short, crossed}",
            r"\shortstack{to close\\$\mathrm{sign}(s)$}",
            r"\shortstack{to close\\$\mathrm{sign}(s)$, crossed}",
            r"\shortstack{to close, $\mathrm{sign}(s)$\\eight forecasts}",
        ],
        body,
    )
    day = t.drop(index="15:30")
    peak = day["as_mid"].idxmax()
    macro("runappPcAsPeak", fnum(t.loc[peak, "as_mid"]))
    macro("runappPcAsPeakClock", peak)
    second = day["as_mid"].drop(index=peak).idxmax()
    macro("runappPcAsSecond", fnum(t.loc[second, "as_mid"]))
    macro("runappPcAsSecondClock", second)
    macro("runappPcAsFirst", fnum(t.loc["09:35", "as_mid"]))
    macro("runappPcAsFirstX", fnum(t.loc["09:35", "as_x"]))
    macro("runappPcSgFirst", fnum(t.loc["09:35", "sg_mid"]))
    macro("runappPcSgFirstX", fnum(t.loc["09:35", "sg_x"]))
    macro("runappPcAsFifteen", fnum(t.loc["15:00", "as_mid"]))
    macro("runappPcAsLast", fnum(t.loc["15:30", "as_mid"]))
    macro("runappPcAsLastX", fnum(t.loc["15:30", "as_x"]))
    macro("runappPcSgLast", fnum(t.loc["15:30", "sg_mid"]))
    macro("runappPcSgLastX", fnum(t.loc["15:30", "sg_x"]))
    macro("runappPcSgLastLo", fnum(t.loc["15:30", "sg_min"]))
    macro("runappPcSgLastHi", fnum(t.loc["15:30", "sg_max"]))
    macro("runappPcDayClocks", str(len(day)))
    macro("runappPcAsBeatsAll", str(int((day["as_mid"] > day["sg_max"]).sum())))
    macro("runappPcAsBeatsAllX", str(int((day["as_x"] > day["sg_x"]).sum())))
    macro("runappPcSgDayLo", fnum(day["sg_mid"].min()))
    macro("runappPcSgDayHi", fnum(day["sg_mid"].max()))
    rp = t.dropna(subset=["rp_as"])
    macro("runappPcRpClocks", str(len(rp)))
    macro("runappPcRpAsLo", fnum(rp["rp_as"].min()))
    macro("runappPcRpAsHi", fnum(rp["rp_as"].max()))
    macro("runappPcRpSgBeats", str(int((rp["rp_sg"] > rp["rp_as"]).sum())))
    # the notebooks' own per-clock tables sit flat on the censored-implied bars;
    # these tables re-invert them.  Report how far apart the two are.
    nb = pd.read_csv(HC / "rule_by_entry_hhmm.csv")
    nb = nb[nb["rule"] == "sign(s)"].set_index("hhmm")["Sharpe_ann"]
    diff = (t["sg_mid"] - nb.reindex(t.index)).abs().dropna()
    macro("runappPcNbDiff", fnum(diff.max()))
    macro("runappPcNbLast", fnum(nb.loc["15:30"]))
    nba = pd.read_csv(HC / "rule_by_entry_hhmm.csv")
    nba = nba[nba["rule"] == "always short"].set_index("hhmm")["Sharpe_ann"]
    assert ((t["as_mid"] - nba.reindex(t.index)).abs().dropna() < TOL).all(), (
        "always short needs no forecast"
    )


# =========================================================================== item 4
def restofday() -> None:
    """Direct rest-of-day forecasts against the one-step construction (QLIKE)."""
    src = RES / "linear_subsection_restofday" / "score_rest_of_day.csv"
    d = pd.read_csv(src, dtype={"clock": str, "bar": str})
    assert (d["train_win"] == 2000).all()
    e = d[d["clock"] != "1530"]
    last = d[d["clock"] == "1530"]
    bucket_lab = {
        "baseline": "HAR + calendar",
        "live_feasible": "live-feasible (16 columns)",
        "all_features": "all features",
    }
    est_lab = {"ridge": "ridge", "reclasso": "lasso", "reclasticnet": "elastic net"}
    body = []
    meds: dict[str, list[float]] = {}
    better: list[int] = []
    worse_sig: list[int] = []
    for b in ["baseline", "all_features"]:  # live_feasible commented out
        for est in ["ridge", "reclasso", "reclasticnet"]:
            g = e[(e["bucket"] == b) & (e["estimator"] == est)]
            assert len(g) == 12, (b, est, len(g))
            g15 = last[(last["bucket"] == b) & (last["estimator"] == est)]
            med = float(g["pct_plain_vs_onestep"].median())
            nb_ = int(
                (
                    (g["pct_plain_vs_onestep"] < 0) & (g["p_plain_vs_onestep"] < ALPHA)
                ).sum()
            )
            nw = int(
                (
                    (g["pct_plain_vs_onestep"] > 0) & (g["p_plain_vs_onestep"] < ALPHA)
                ).sum()
            )
            npw = int((g["pct_plain_vs_onestep"] > 0).sum())
            meds.setdefault(b, []).append(med)
            better.append(nb_)
            worse_sig.append(nw)
            body.append(
                row(
                    [
                        bucket_lab[b],
                        est_lab[est],
                        f"{fint(g['n'].min())}--{fint(g['n'].max())}",
                        fnum(med, 1),
                        str(nb_),
                        str(nw),
                        str(npw),
                        fnum(float(g15["pct_plain_vs_onestep"].abs().iloc[0]), 3),
                    ]
                )
            )
        if b != "all_features":
            body.append(r"\midrule")
    write_tab(
        "restofday",
        [
            src.relative_to(ROOT).as_posix()
            + ' ("plain" columns: qlike_plain, pct_plain_vs_onestep, p_plain_vs_onestep)'
        ],
        "llrrrrrr",
        [
            "column set",
            "estimator",
            "sessions",
            r"median~~$\Delta$QLIKE (\%)",
            "clocks~~better",
            "clocks~~worse",
            "clocks higher~~(point)",
            r"15:30~~$|\Delta|$ (\%)",
        ],
        body,
    )
    for b, nm in (
        ("baseline", "Base"),
        ("live_feasible", "Live"),
        ("all_features", "All"),
    ):
        v = meds[b]
        # most negative first: the range reads "from -x to -y"
        macro(f"runappRd{nm}Lo", fnum(min(v), 0))
        macro(f"runappRd{nm}Hi", fnum(max(v), 0))
    macro("runappRdBetterLo", str(min(better)))
    macro("runappRdBetterHi", str(max(better)))
    assert max(worse_sig) == 0, "the direct forecast is never significantly worse"
    macro("runappRdNlo", fint(d["n"].min()))
    macro("runappRdNhi", fint(d["n"].max()))
    macro("runappRdFirst", str(d["first"].min()))
    macro("runappRdLast", str(d["last"].max()))
    macro("runappRdLastMax", fnum(float(last["pct_plain_vs_onestep"].abs().max()), 3))
    macro("runappRdAlpha", fnum(ALPHA, 2))
    # extreme plain back-transforms (QLIKE above 1 on either side), named in the text
    ext = e[(e["qlike_plain"] > 1) | (e["qlike_onestep"] > 1)]
    macro("runappRdExtremeN", str(len(ext)))
    macro("runappRdCells", str(len(e)))
    assert not (ext["p_plain_vs_onestep"] < ALPHA).any(), (
        "no extreme cell is a significant comparison"
    )
    big = ext.sort_values("qlike_plain").iloc[-1]
    macro("runappRdExtremeQ", fnum(float(big["qlike_plain"]), 1))
    macro("runappRdExtremeOne", fnum(float(big["qlike_onestep"]), 3))
    macro("runappRdExtremeClock", f"{big['clock'][:2]}:{big['clock'][2:]}")
    macro(
        "runappRdExtremeCell",
        f"{bucket_lab[big['bucket']]} {est_lab[big['estimator']]}",
    )
    # 15:30 all-features ridge: the plain back-transform's rare extreme values
    r15 = last[
        (last["bucket"] == "all_features") & (last["estimator"] == "ridge")
    ].iloc[0]
    macro("runappRdAllRidgeLast", fnum(float(r15["qlike_plain"]), 2))

    restofday_trade()


def restofday_trade() -> None:
    """Optional: the trading test of the direct forecast (another workstream's output).

    Its table is that workstream's generated/appendix_running_restofday_trading.tex;
    this writes only the numbers the prose quotes, to a separate macro file, and only
    when the test's pooled CSV exists (the section inputs both under IfFileExists).
    """
    src = (
        RES / "linear_subsection_restofday" / "trading_test" / "trading_test_pooled.csv"
    )
    out = GEN / "appendix_running_restofday_trade_numbers.tex"
    if not src.exists():
        if out.exists():
            out.unlink()
        return
    t = pd.read_csv(src)
    t = t[t["pool"] == "10:00-15:30"]
    nums: dict[str, str] = {}

    def cell(est: str, bucket: str, variant: str, fill: str) -> pd.Series:
        r = t[
            (t["estimator"] == est)
            & (t["bucket"] == bucket)
            & (t["variant"] == variant)
            & (t["fill"] == fill)
        ]
        assert len(r) == 1, (est, bucket, variant, fill)
        return r.iloc[0]

    for bucket, nm in (
        ("live_feasible", "Lf"),
        ("all_features", "Af"),
        ("baseline", "Ba"),
    ):
        for fill, fx in (("mid", ""), ("crossed", "X")):
            r = cell("ridge", bucket, "plain", fill)
            nums[f"runappTt{nm}Cur{fx}"] = fnum(r["Sharpe_current"])
            nums[f"runappTt{nm}Dir{fx}"] = fnum(r["Sharpe_direct"])
            nums[f"runappTt{nm}D{fx}"] = fnum(r["dSharpe"], 2, plus=True)
            nums[f"runappTt{nm}Ci{fx}"] = fci(r["dSharpe_pct_lo"], r["dSharpe_pct_hi"])
        r = cell("ridge", bucket, "plain", "mid")
        nums[f"runappTt{nm}BuyCur"] = fnum(r["pct_buy_current"], 1)
        nums[f"runappTt{nm}BuyDir"] = fnum(r["pct_buy_direct"], 1)
        nums[f"runappTt{nm}Q"] = fnum(r["pct_qlike_direct_vs_current"], 1)
        nums[f"runappTt{nm}VsShort"] = fnum(r["dSharpe_direct_vs_short"], 2)
        nums[f"runappTt{nm}VsShortCi"] = fci(
            r["dSharpe_direct_vs_short_pct_lo"], r["dSharpe_direct_vs_short_pct_hi"]
        )
    ridge = t[(t["estimator"] == "ridge") & (t["variant"] == "plain")]
    n_int = len(ridge)
    n_zero = int(((ridge["dSharpe_pct_lo"] < 0) & (ridge["dSharpe_pct_hi"] > 0)).sum())
    nums["runappTtRidgeIntervals"] = str(n_int)
    nums["runappTtRidgeZero"] = str(n_zero)
    mid = t[t["fill"] == "mid"]
    nums["runappTtCombos"] = str(len(mid))
    nums["runappTtAhead"] = str(int((mid["dSharpe"] > 0).sum()))
    exc = (mid["dSharpe_pct_lo"] > 0) & (mid["dSharpe_basic_lo"] > 0)
    exc_neg = (mid["dSharpe_pct_hi"] < 0) & (mid["dSharpe_basic_hi"] < 0)
    nums["runappTtExclFor"] = str(int(exc.sum()))
    nums["runappTtExclAgainst"] = str(int(exc_neg.sum()))
    lines = [
        "% AUTO-GENERATED by writeup/make_appendix_running_tex.py -- do not edit.",
        f"% Source: {src.relative_to(ROOT).as_posix()} (pool 10:00-15:30; per-bar ridge, plain back-transform unless counted over all)",
    ]
    lines += [r"\newcommand{\%s}{%s}" % (k, v) for k, v in nums.items()]
    out.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


# =========================================================================== item 5
def post2024() -> None:
    """The long-only card after the research span: studies 85, 87, 88, 89, 90."""
    s87 = pd.read_csv(PROP / "87" / "summary.csv").set_index("variant")
    s88 = pd.read_csv(PROP / "88" / "summary.csv")
    s88 = s88[s88["N"] == 250]
    s89 = pd.read_csv(PROP / "89" / "summary.csv")
    s89 = s89[s89["close"] == "official_close"]
    s90 = pd.read_csv(PROP / "90" / "summary.csv").set_index("rule")
    fd89 = pd.read_csv(PROP / "89" / "forecast_diagnostics.csv")

    def g88(span: str, rule: str) -> pd.Series:
        r = s88[(s88["span"] == span) & (s88["rule"] == rule)]
        assert len(r) == 1, (span, rule)
        return r.iloc[0]

    def g89(var: str, period: str) -> pd.Series:
        r = s89[(s89["variant"] == var) & (s89["period"] == period)]
        assert len(r) == 1, (var, period)
        return r.iloc[0]

    def pt(p: float, t: float, d: int = 4) -> str:
        return f"{fnum(p, d)} ({fnum(t, 2)})"

    f0r, f0p = g88("research", "F0"), g88("post", "F0")
    # the card is one table across studies 88, 89 (official close) and 90
    assert abs(f0p["pnl_day"] - g89("F0", "post")["pnl_day"]) < TOL
    assert abs(f0p["pnl_day"] - s90.loc["F0 card", "post_pnl"]) < 1e-5
    assert abs(f0r["pnl_day"] - s90.loc["F0 card", "research_pnl"]) < 1e-5
    ncol = 5
    body = [
        panel(r"(a) the card and walk-forward variants (studies 88 and 90)", ncol),
        row(
            [
                r"card: buy iff ask $\le P^{*}$",
                f"{fnum(100 * f0r['share'], 0)} / {fnum(100 * f0p['share'], 0)}",
                pt(f0r["pnl_day"], f0r["t_pnl"]),
                pt(f0p["pnl_day"], f0p["t_pnl"]),
                "---",
            ]
        ),
    ]
    lab88 = {
        "F1": "88: trailing-optimal multiplier on $P^{*}$",
        "F2": "88: regression of $R$ on $\\log(P^{*}/\\text{ask})$",
        "F3": "88: premium tightened by trailing realized/implied",
    }
    for rule, lab in lab88.items():
        rr, rp = g88("research", rule), g88("post", rule)
        body.append(
            row(
                [
                    lab,
                    f"{fnum(100 * rr['share'], 0)} / {fnum(100 * rp['share'], 0)}",
                    pt(rr["pnl_day"], rr["t_pnl"]),
                    pt(rp["pnl_day"], rp["t_pnl"]),
                    f"{fnum(rp['d_vs_F0'], 4, plus=True)} {fci(rp['d_ci_lo'], rp['d_ci_hi'], 3)}",
                ]
            )
        )
    lab90 = {
        "C1 VIX tercile": "90: VIX tercile",
        "C2 morning realized tercile": "90: realized variance so far, tercile",
        "C3 FOMC day": "90: FOMC statement day",
        "C5 cushion tercile": "90: implied over trailing realized, tercile",
        "C4 own form (last 20 buys)": "90: the card's last 20 buys",
    }
    for rule, lab in lab90.items():
        r = s90.loc[rule]
        body.append(
            row(
                [
                    lab,
                    f"{fnum(100 * r['research_share'], 0)} / {fnum(100 * r['post_share'], 0)}",
                    pt(r["research_pnl"], r["research_t"]),
                    pt(r["post_pnl"], r["post_t"]),
                    f"{fnum(r['post_diff'], 4, plus=True)} {fci(r['post_lo'], r['post_hi'], 3)}",
                ]
            )
        )
    fr, fp = g89("F0", "research"), g89("F0", "post")
    assert int(fp["days"]) == int(f0p["days"]), (
        "study 89's post-2024 days are study 88's"
    )
    body += [
        r"\midrule",
        panel(r"(b) training windows and trade-aligned targets (study 89)", ncol),
    ]
    lab89 = {
        "TW1000": "training window 1000 sessions (card: 2000)",
        "TW500": "training window 500 sessions",
        "TW250": "training window 250 sessions",
        "ridge_250": r"target $\log(RV/\mathrm{IV}^2_{\text{ask}})$, ridge, 250 days",
        "logit_250": r"target $R>0$, logistic, 250 days",
        "ridge_500": r"target $\log(RV/\mathrm{IV}^2_{\text{ask}})$, ridge, 500 days",
    }
    for var, lab in lab89.items():
        rr, rp = g89(var, "research"), g89(var, "post")
        body.append(
            row(
                [
                    lab,
                    f"{fnum(100 * rr['share'], 0)} / {fnum(100 * rp['share'], 0)}",
                    pt(rr["pnl_day"], rr["t_pnl"]),
                    pt(rp["pnl_day"], rp["t_pnl"]),
                    f"{fnum(rp['diff_vs_F0'], 4, plus=True)} {fci(rp['diff_ci_lo'], rp['diff_ci_hi'], 3)}",
                ]
            )
        )
    # study 87: the research years with the post-2024 inputs
    dk = s87.loc["deck"]
    body += [
        r"\midrule",
        panel(
            r"(c) the research years rerun with the post-2024 inputs (study 87)", ncol
        ),
    ]
    lab87 = {
        "deck": "research card (per-bar ridge, live-feasible columns)",
        "T1": "free-feed column set",
        "T2": "VIX family as hourly prints",
        "T3": "ES moments rescaled to the new vendor",
        "ALL": "all three together",
    }
    for var, lab in lab87.items():
        r = s87.loc[var]
        dcell = (
            "---"
            if var == "deck"
            else f"{fnum(r['d_pnl'], 4, plus=True)} {fci(r['d_ci_lo'], r['d_ci_hi'], 3)}"
        )
        body.append(
            row(
                [
                    lab,
                    f"{fnum(100 * r['buys'] / r['days'], 0)}",
                    pt(r["pnl_per_day"], r["t_pnl"]),
                    "---",
                    dcell,
                ]
            )
        )
    write_tab(
        "post2024",
        [
            "results/atm_straddle_intraday_holdclose/proposals/88/summary.csv (N = 250)",
            "results/atm_straddle_intraday_holdclose/proposals/90/summary.csv",
            "results/atm_straddle_intraday_holdclose/proposals/89/summary.csv (official close)",
            "results/atm_straddle_intraday_holdclose/proposals/87/summary.csv",
        ],
        "lrrrr",
        [
            "",
            r"\% days bought~~research / after",
            r"research~~P\&L/day ($t$)",
            r"after 2024-05~~P\&L/day ($t$)",
            r"minus the card~~[95\%]",
        ],
        body,
    )
    macro("runappPoEightyNineResDays", fint(fr["days"]))
    macro("runappPoEightySevenDays", fint(dk["days"]))
    pl = s87.loc["post_live"]
    macro("runappPoSpxDays", fint(pl["days"]))
    macro("runappPoSpxBuys", fint(pl["buys"]))
    macro("runappPoSpxPnl", fnum(pl["pnl_per_day"], 4))
    macro("runappPoSpxT", fnum(pl["t_pnl"], 2))
    macro("runappPoResPnl", fnum(f0r["pnl_day"], 4))
    macro("runappPoResT", fnum(f0r["t_pnl"], 2))
    macro("runappPoResDays", fint(f0r["days"]))
    macro("runappPoPostPnl", fnum(f0p["pnl_day"], 4))
    macro("runappPoPostT", fnum(f0p["t_pnl"], 2))
    macro("runappPoPostDays", fint(f0p["days"]))
    macro("runappPoPostCi", fci(f0p["pnl_ci_lo"], f0p["pnl_ci_hi"], 3))
    macro("runappPoResShare", fnum(100 * f0r["share"], 0))
    macro("runappPoPostShare", fnum(100 * f0p["share"], 0))
    macro("runappPoDeckPnl", fnum(dk["pnl_per_day"], 4))
    al = s87.loc["ALL"]
    macro("runappPoAllPnl", fnum(al["pnl_per_day"], 4))
    macro("runappPoAllD", fnum(al["d_pnl"], 4))
    macro("runappPoAllCi", fci(al["d_ci_lo"], al["d_ci_hi"], 3))
    alone = s87.loc[["T1", "T2", "T2m", "T3"], "d_pnl"].abs().max()
    macro("runappPoAloneMax", fnum(alone, 3))
    f1r, f1p = g88("research", "F1"), g88("post", "F1")
    macro("runappPoFOnePost", fnum(f1p["pnl_day"], 4))
    macro("runappPoFOneT", fnum(f1p["t_pnl"], 2))
    macro("runappPoFOneCi", fci(f1p["pnl_ci_lo"], f1p["pnl_ci_hi"], 3))
    macro("runappPoFOneD", fnum(f1p["d_vs_F0"], 3))
    macro("runappPoFOneDCi", fci(f1p["d_ci_lo"], f1p["d_ci_hi"], 3))
    macro("runappPoFOneHolm", fnum(f1p["p_d_holm"], 3))
    macro("runappPoFOneResD", fnum(f1r["d_vs_F0"], 3))
    macro("runappPoFOneResDCi", fci(f1r["d_ci_lo"], f1r["d_ci_hi"], 3))
    tw = [g89(v, "post")["pnl_day"] for v in ("TW1000", "TW500", "TW250")]
    macro("runappPoTwLo", fnum(min(tw), 3))
    macro("runappPoTwHi", fnum(max(tw), 3))
    ratio = s89[s89["variant"].str.contains("_") & (s89["period"] == "post")]
    macro("runappPoRatioShareLo", fnum(100 * ratio["share"].min(), 0))
    macro("runappPoRatioShareHi", fnum(100 * ratio["share"].max(), 0))
    macro("runappPoRatioPnlLo", fnum(ratio["pnl_day"].min(), 3))
    macro("runappPoRatioPnlHi", fnum(ratio["pnl_day"].max(), 3))
    fdp = fd89[fd89["period"] == "post"].set_index("forecast")
    macro("runappPoQCard", fnum(fdp.loc["rv_hat_F0", "qlike"], 3))
    macro("runappPoQAsk", fnum(fdp.loc["IVask", "qlike"], 3))
    models = fdp.loc[[i for i in fdp.index if i.startswith("rv_hat")], "qlike"]
    macro("runappPoQModelLo", fnum(models.min(), 3))
    macro("runappPoQModelHi", fnum(models.max(), 3))
    assert fdp.loc["IVask", "qlike"] < models.min()
    fdr = fd89[fd89["period"] == "research"].set_index("forecast")
    macro("runappPoQCardRes", fnum(fdr.loc["rv_hat_F0", "qlike"], 3))
    macro("runappPoQAskRes", fnum(fdr.loc["IVask", "qlike"], 3))
    c4 = s90.loc["C4 own form (last 20 buys)"]
    macro("runappPoCFourPost", fnum(c4["post_pnl"], 4))
    macro("runappPoCFourCi", fci(c4["post_lo"], c4["post_hi"], 3))
    others = s90.drop(index=["F0 card", "C4 own form (last 20 buys)"])
    assert (others["post_pnl"] < 0).all()
    assert ((s90["post_lo"] <= 0) & (s90["post_hi"] >= 0)).all(), (
        "every post-2024 interval of study 90 spans 0"
    )


# =========================================================================== decision time
def decision() -> None:
    """Study 80 (the decision clock on the 866 days) and study 86 (SPX, 2024-12 on)."""
    s80 = pd.read_csv(PROP / "80" / "summary_by_horizon.csv")
    b80 = pd.read_csv(PROP / "80" / "bootstrap_diff.csv")
    s80 = s80[s80["scope"] == "all_days"].copy()
    s80["h"] = s80["h"].astype(int)
    b80 = b80[b80["scope"] == "all_days"].set_index("h_minus_1")
    body = []
    for _, r in s80.iterrows():
        h = int(r["h"])
        dcell = "---"
        if h > 1:
            b = b80.loc[f"{h}-1"]
            dcell = f"{fnum(b['point'], 3, plus=True)} {fci(b['ci_lo_95'], b['ci_hi_95'], 3)}"
        body.append(
            row(
                [
                    str(h),
                    str(r["decision_stamp"]),
                    fnum(r["qlike"], 4),
                    fint(r["traded_ask"]),
                    fnum(r["mean_R_ask"], 3),
                    fnum(r["t_ask"], 2),
                    fnum(r["mean_pnl_per_day_ask"], 4),
                    dcell,
                ]
            )
        )
    write_tab(
        "decision80",
        [
            "results/atm_straddle_intraday_holdclose/proposals/80/summary_by_horizon.csv (scope all_days)",
            "results/atm_straddle_intraday_holdclose/proposals/80/bootstrap_diff.csv (scope all_days)",
        ],
        "lrrrrrrr",
        [
            "$h$",
            "last~~input",
            "QLIKE~~16:00 bar",
            "days~~bought",
            "mean $R$~~bought",
            "$t$",
            r"P\&L/day",
            r"minus $h=1$~~[95\%]",
        ],
        body,
    )
    h1 = s80[s80["h"] == 1].iloc[0]
    h2 = s80[s80["h"] == 2].iloc[0]
    macro("runappDtDays", fint(h1["days"]))
    macro("runappDtOneR", fnum(h1["mean_R_ask"], 3))
    macro("runappDtOneT", fnum(h1["t_ask"], 2))
    macro("runappDtOneN", fint(h1["traded_ask"]))
    macro("runappDtTwoR", fnum(h2["mean_R_ask"], 3))
    macro("runappDtTwoT", fnum(h2["t_ask"], 2))
    macro("runappDtTwoD", fnum(b80.loc["2-1", "point"], 3))
    macro(
        "runappDtTwoCi", fci(b80.loc["2-1", "ci_lo_95"], b80.loc["2-1", "ci_hi_95"], 3)
    )
    assert (b80["ci_hi_95"] < 0).all(), (
        "every earlier clock is below 15:30 with the interval"
    )
    nme = pd.read_csv(PROP / "80" / "summary_by_horizon.csv")
    nme = nme[(nme["scope"] == "non_month_end") & (nme["h"].astype(str) != "1")]
    assert (nme["mean_R_ask"] < 0).all()

    # ---- study 86, SPX book
    s86 = pd.read_csv(PROP / "86" / "spx_summary_tau.csv")
    b86 = pd.read_csv(PROP / "86" / "spx_bootstrap_tau.csv")
    me86 = pd.read_csv(PROP / "86" / "spx_month_end_tau.csv").set_index("tau")
    t0 = s86[s86["model"] == "T0"].set_index("tau")
    bb = b86[(b86["model"] == "T0") & (b86["stat"] == "pnl_ask")].set_index(
        "tau_minus_1530"
    )
    body = []
    for tau, r in t0.iterrows():
        if tau == "15:30":
            dcell, holm = "---", "---"
        else:
            b = bb.loc[tau]
            dcell = f"{fnum(b['point'], 3, plus=True)} {fci(b['ci_lo'], b['ci_hi'], 3)}"
            holm = fnum(b["holm_boot_1s"], 2)
        me = me86.loc[tau]
        body.append(
            row(
                [
                    tau,
                    fint(r["traded_ask"]),
                    fnum(r["pnl_per_day_ask"], 4),
                    fnum(r["t_pnl_day_ask"], 2),
                    dcell,
                    holm,
                    fnum(me["mean_R_ask"], 3),
                    fnum(me["t_ask"], 2),
                ]
            )
        )
    write_tab(
        "decision86",
        [
            "results/atm_straddle_intraday_holdclose/proposals/86/spx_summary_tau.csv (model T0)",
            "results/atm_straddle_intraday_holdclose/proposals/86/spx_bootstrap_tau.csv (T0, pnl_ask)",
            "results/atm_straddle_intraday_holdclose/proposals/86/spx_month_end_tau.csv",
        ],
        "lrrrrrrr",
        [
            r"$\tau$",
            "days~~bought",
            r"P\&L/day",
            "$t$",
            r"minus 15:30~~[95\%]",
            "Holm $p$",
            "month-end~~mean $R$",
            "month-end~~$t$",
        ],
        body,
    )
    macro("runappDsDays", fint(t0["days"].iloc[0]))
    macro("runappDsMonthEnds", fint(me86["month_ends"].iloc[0]))
    macro("runappDsHolmMin", fnum(b86["holm_boot_1s"].min(), 3))
    tmax = max(s86["t_pnl_day_ask"].abs().max(), s86["t_pnl_day_mid"].abs().max())
    macro("runappDsTmax", fnum(tmax, 2))
    macro("runappDsMeLast", fnum(me86.loc["15:30", "mean_R_ask"], 3))
    macro("runappDsMeLastT", fnum(me86.loc["15:30", "t_ask"], 2))
    later = me86.loc[["15:40", "15:45", "15:50"], "minus_1530_R_ask"]
    macro("runappDsMeLaterLo", fnum(later.min(), 2))
    macro("runappDsMeLaterHi", fnum(later.max(), 2))
    macro("runappDsMeHolmMin", fnum(me86["holm_paired_1s"].min(), 2))
    macro("runappDsSpreadLo", fnum(100 * t0["rel_spread_median"].min(), 1))
    macro("runappDsSpreadHi", fnum(100 * t0["rel_spread_median"].max(), 1))
    xsp = pd.read_csv(PROP / "86" / "summary_tau.csv")
    xsp = xsp[xsp["model"] == "T0"]
    macro("runappDsXspSpreadLo", fnum(100 * xsp["rel_spread_median"].min(), 1))
    macro("runappDsXspSpreadHi", fnum(100 * xsp["rel_spread_median"].max(), 1))
    # the session range, from the study's saved summary
    txt = (PROP / "86" / "summary.txt").read_text(encoding="utf-8")
    m = re.search(
        r"card rule on SPX .*?(\d+) sessions \((\d{4}-\d\d-\d\d) \.\. (\d{4}-\d\d-\d\d)\)",
        txt,
    )
    assert m and int(m.group(1)) == int(t0["days"].iloc[0])
    macro("runappDsFirst", m.group(2))
    macro("runappDsLast", m.group(3))

    # ---- study 82: one-minute inputs on the 15:30 forecast
    q82 = pd.read_csv(PROP / "82" / "qlike_1530.csv")
    q82 = q82[q82["min_train"] == 150].set_index("model")
    fine = q82.loc[["S4_+fine", "S5_+mom30+fine", "L4r_recal+fine"]]
    macro("runappDgFineLo", fnum(100 * fine["dqlike_pct"].min(), 1))
    macro("runappDgFineHi", fnum(100 * fine["dqlike_pct"].max(), 1))
    macro("runappDgFineDm", fnum(fine["dm_t_nw5"].abs().max(), 2))
    macro("runappDgDays", fint(q82["oos_days"].iloc[0]))
    macro("runappDgLong", fnum(100 * q82.loc["L0_long", "dqlike_pct"], 1))
    # ---- study 84: how long the limit order should work (SPX book)
    c84 = pd.read_csv(PROP / "84" / "spx_cancel_table.csv")
    c84 = c84[(c84["model"] == "conservative") & (c84["t0"] == "15:30")].set_index(
        "min_after_t0"
    )
    macro("runappLoDays", fint(c84.loc[0, "days"]))
    macro("runappLoOnce", fnum(c84.loc[0, "mean_per_day"], 4))
    macro("runappLoOnceT", fnum(c84.loc[0, "t"], 2))
    macro("runappLoOneMin", fnum(c84.loc[1, "gain_vs_immediate"], 3))
    macro("runappLoOneMinT", fnum(c84.loc[1, "t_gain"], 2))


# =========================================================================== month-end long
def monthend() -> None:
    """Study 83: the month-end long straddle by entry clock."""
    src = PROP / "83" / "summary.txt"
    txt = src.read_text(encoding="utf-8")
    m = re.search(
        r"month-ends with a 16:00 close and a quote at every clock: (\d+) \((\S+) \.\. (\S+)\)",
        txt,
    )
    assert m
    n_me, first, last = int(m.group(1)), m.group(2), m.group(3)
    pat = re.compile(
        r"^(\d\d:\d\d)\s+([\d.]+)\s+([\d.]+)%\s+([+-][\d.]+)\s+([\d.]+)\s+(\d+)%\s+(?:\(base\)|([+-][\d.]+)\s+([+-]?[\d.]+)\s+([\d.]+))\s*$",
        re.M,
    )
    rows_ = pat.findall(txt)
    assert len(rows_) == 13, len(rows_)
    per = pd.read_csv(PROP / "83" / "month_end_by_clock.csv")
    body = []
    for ck, ask, spr, mr, tr, hit, dd, td, ph in rows_:
        g = per[per["clock"] == ck]["R"]
        assert len(g) == n_me and abs(g.mean() - float(mr)) < 5e-4, (
            ck
        )  # the CSV reproduces the summary
        body.append(
            row(
                [
                    ck,
                    ask,
                    spr,
                    fnum(float(mr), 3),
                    fnum(float(tr), 2),
                    hit,
                    fnum(float(dd), 3, plus=True) if dd else "---",
                    fnum(float(td), 2) if td else "---",
                    fnum(float(ph), 2) if ph else "---",
                ]
            )
        )
    write_tab(
        "monthend",
        [
            src.relative_to(ROOT).as_posix(),
            "results/atm_straddle_intraday_holdclose/proposals/83/month_end_by_clock.csv (gate: mean R)",
        ],
        "lrrrrrrrr",
        [
            "entry",
            "median~~ask",
            r"median~~spread (\%)",
            "mean $R$",
            "$t$",
            r"hit (\%)",
            "minus 15:30",
            "paired $t$",
            "Holm $p$",
        ],
        body,
    )
    macro("runappMeN", str(n_me))
    macro("runappMeFirst", first)
    macro("runappMeLast", last)
    last_row = [r for r in rows_ if r[0] == "15:30"][0]
    macro("runappMeR", fnum(float(last_row[3]), 3))
    macro("runappMeT", fnum(float(last_row[4]), 2))
    m1 = re.search(
        r"first half \((\d+) month-ends, (\S+) \.\. (\S+)\):.*?15:30 ([+-][\d.]+)", txt
    )
    m2 = re.search(
        r"second half \((\d+) month-ends, (\S+) \.\. (\S+)\):.*?15:30 ([+-][\d.]+)", txt
    )
    assert m1 and m2
    macro("runappMeFirstHalf", fnum(float(m1.group(4)), 3))
    macro("runappMeSecondHalf", fnum(float(m2.group(4)), 3))
    macro("runappMeSplit", m2.group(2))
    early = [float(r[3]) for r in rows_ if r[0] != "15:30"]
    macro("runappMeEarlyLo", fnum(min(early), 3))
    macro("runappMeEarlyHi", fnum(max(early), 3))
    holm = [float(r[8]) for r in rows_ if r[8]]
    macro("runappMeHolmMin", fnum(min(holm), 2))


# =========================================================================== VIX only
def vixonly() -> None:
    src = CL / "vix_bucket.csv"
    v = pd.read_csv(src)
    body = []
    prev = None
    for _, r in v.iterrows():
        if prev is not None and r["column set"] != prev:
            body.append(r"\midrule")
        prev = r["column set"]
        body.append(
            row(
                [
                    tex_escape(r["column set"]),
                    {"enet": "elastic net"}.get(r["estimator"], r["estimator"]),
                    fnum(r["16:00 QLIKE vs live-feasible (%)"], 2, plus=True),
                    fnum(r["13-bar mean QLIKE vs live-feasible (%)"], 2, plus=True),
                    fnum(r["Sharpe mid (research scorer)"], 2),
                    fnum(r["Sharpe crossed (research scorer)"], 2),
                ]
            )
        )
    write_tab(
        "vixonly",
        [
            src.relative_to(ROOT).as_posix()
            + " (research-scorer columns only; the notebook-scorer Sharpe ratios are quoted in the text)"
        ],
        "llrrrr",
        [
            "column set",
            "estimator",
            r"16:00 QLIKE vs~~live-feasible (\%)",
            r"13-bar QLIKE vs~~live-feasible (\%)",
            "Sharpe~~(mid)",
            "Sharpe~~(crossed)",
        ],
        body,
    )
    vi = v.set_index(["estimator", "column set"])
    rv = vi.loc[("ridge", "HAR + calendar + VIX only")]
    rl = vi.loc[("ridge", "live-feasible (16 columns)")]
    rm = vi.loc[("ridge", "live-feasible minus VVIX and VIX3M")]
    rf = vi.loc[("ridge", "free feed (ES 1-min bars + VIX + FOMC calendar)")]
    macro("runappVxQ", fnum(rv["16:00 QLIKE vs live-feasible (%)"], 1))
    macro(
        "runappVxQThirteen",
        fnum(rv["13-bar mean QLIKE vs live-feasible (%)"], 1, plus=True),
    )
    macro("runappVxMid", fnum(rv["Sharpe mid (research scorer)"]))
    macro("runappVxX", fnum(rv["Sharpe crossed (research scorer)"]))
    macro("runappVxLfMid", fnum(rl["Sharpe mid (research scorer)"]))
    macro("runappVxLfX", fnum(rl["Sharpe crossed (research scorer)"]))
    macro("runappVxNbMid", fnum(rv["Sharpe mid (this notebook)"]))
    macro("runappVxNbLfMid", fnum(rl["Sharpe mid (this notebook)"]))
    macro("runappVxMinusQ", fnum(rm["16:00 QLIKE vs live-feasible (%)"], 2))
    macro("runappVxFreeQ", fnum(rf["16:00 QLIKE vs live-feasible (%)"], 2))
    macro("runappVxFreeMid", fnum(rf["Sharpe mid (research scorer)"]))
    macro("runappVxDays", fint(v["n days"].iloc[0]))
    # every estimator: the VIX-only set trades below the live-feasible set (research scorer)
    for est in ("ridge", "lasso", "enet"):
        assert (
            vi.loc[(est, "HAR + calendar + VIX only"), "Sharpe mid (research scorer)"]
            < vi.loc[
                (est, "live-feasible (16 columns)"), "Sharpe mid (research scorer)"
            ]
        ) or est == "enet"
    # design-column key from the loader itself
    sys.path.insert(0, str(ROOT))
    from src.data.loading import SUBGROUPS  # noqa: PLC0415

    lf = SUBGROUPS["live_feasible"]
    assert (
        len(lf) == 16
        and len(SUBGROUPS["live_vix_only"]) == 14
        and len(SUBGROUPS["free_vix_only"]) == 13
    )
    assert SUBGROUPS["vix_only"] == ["vix"]
    macro("runappKeyLive", ", ".join(r"\texttt{" + tex_escape(c) + "}" for c in lf))
    dropped = [c for c in lf if c not in SUBGROUPS["free_vix_only"]]
    macro(
        "runappKeyFreeDrop",
        ", ".join(r"\texttt{" + tex_escape(c) + "}" for c in dropped),
    )


# =========================================================================== per-bar vs pooled
def perbar_pooled() -> None:
    src = CL / "perbar_vs_pooled_qlike.csv"
    p = pd.read_csv(src)
    body = []
    sess_ci_below = 0
    for f, g in p.groupby("forecast", sort=False):
        g = g.set_index("bar end")
        bars = g.drop(index="session mean")
        better = int((bars["ci_hi (%)"] < 0).sum())
        worse = int((bars["ci_lo (%)"] > 0).sum())
        sm = g.loc["session mean"]
        sess_ci_below += int(sm["ci_hi (%)"] < 0)

        def cell(bar: str) -> str:
            r = g.loc[bar]
            return f"{fnum(r['difference (%)'], 1, plus=True)} {fci(r['ci_lo (%)'], r['ci_hi (%)'], 1)}"

        body.append(
            row(
                [
                    tex_escape(str(f)),
                    cell("session mean"),
                    fnum(sm["DM t"], 2),
                    cell("14:30"),
                    cell("15:00"),
                    cell("16:00"),
                    str(better),
                    str(worse),
                ]
            )
        )
    write_tab(
        "perbar_pooled",
        [src.relative_to(ROOT).as_posix()],
        "lrrrrrrr",
        [
            "per-bar forecast",
            r"session mean~~(\%) [95\%]",
            "DM $t$",
            r"14:30 bar~~(\%) [95\%]",
            r"15:00 bar~~(\%) [95\%]",
            r"16:00 bar~~(\%) [95\%]",
            "bars~~better",
            "bars~~worse",
        ],
        body,
    )
    sm = p[p["bar end"] == "session mean"]
    macro("runappPbSessLo", fnum(sm["difference (%)"].min(), 1))
    macro("runappPbSessHi", fnum(sm["difference (%)"].max(), 1))
    macro("runappPbSessCi", str(sess_ci_below))
    macro("runappPbN", str(len(sm)))
    b = p[p["bar end"] == "14:30"]
    macro("runappPbFomcBarLo", fnum(b["difference (%)"].min(), 1))
    macro("runappPbFomcBarHi", fnum(b["difference (%)"].max(), 1))
    macro("runappPbDays", fint(p["days"].iloc[0]))
    h16 = p[(p["bar end"] == "16:00") & (p["ci_hi (%)"] < 0)]
    assert len(h16) == 1
    r16 = h16.iloc[0]
    macro("runappPbSixteenWho", tex_escape(str(r16["forecast"])))
    macro("runappPbSixteen", fnum(r16["difference (%)"], 1))
    macro("runappPbSixteenCi", fci(r16["ci_lo (%)"], r16["ci_hi (%)"], 1))
    # the FOMC split of the 14:30 bar lives only in the notebook's saved output
    txt = nb_output(NB_RVIV, "split by FOMC statement days")
    m = re.search(r"FOMC statement days \((\d+)\)\s+other days \((\d+)\)", txt)
    assert m
    macro("runappPbFomcDays", m.group(1))
    macro("runappPbOtherDays", m.group(2))
    seg = txt.split("split by FOMC statement days", 1)[1]
    vals = re.findall(
        r"^\S.*?\s+(" + FLOAT + r")\s+(" + FLOAT + r")\s+(" + FLOAT + r")\s*$",
        seg,
        re.M,
    )
    assert len(vals) == len(sm), vals
    fomc = [float(a) for a, _, _ in vals]
    other = [float(bb) for _, bb, _ in vals]
    share = [float(c) for _, _, c in vals]
    macro("runappPbFomcLo", fnum(min(fomc), 0))
    macro("runappPbFomcHi", fnum(max(fomc), 0))
    macro("runappPbOtherLo", fnum(min(other), 0))
    macro("runappPbOtherHi", fnum(max(other), 0))
    macro("runappPbShareLo", fnum(min(share), 2))
    macro("runappPbShareHi", fnum(max(share), 2))


# =========================================================================== multi-horizon
def multihorizon() -> None:
    src = RES / "multihorizon" / "ttc_close_fomc1_pooled.csv"
    p = pd.read_csv(src)
    lab = {
        "M0": "M0: per-clock mean of past $\\log RV^{\\mathrm{rem}}$ (no model)",
        "M1": "M1: $\\log$ of the next-bar forecast",
        "M2": "M2: M1 + realized variance so far",
        "M2pooled": "M2, one fit with clock dummies",
        "M3": "M3: M2 + yesterday's $RV^{\\mathrm{rem}}$",
    }
    body = []
    for k, text in lab.items():
        cells = [text]
        for era in ("all", "post2016"):
            e = p[p["era"] == era].set_index("forecast")
            if k == "M0":
                cells += [fnum(e.loc["M0", "qlike"], 4), "---", "---"]
            else:
                cells += [
                    fnum(e.loc[f"a0_{k}", "qlike"], 4),
                    fnum(e.loc[f"blk2_{k}", "qlike"], 4),
                    fnum(e.loc[f"blk2_{k}", "dm_blk2_vs_a0"], 2),
                ]
        body.append(row(cells))
    ea = p[p["era"] == "all"].set_index("forecast")
    eb = p[p["era"] == "post2016"].set_index("forecast")
    # the day ranges, from the forecast file behind the table
    fc = pd.read_parquet(
        RES / "multihorizon" / "ttc_close_fomc1_forecasts.parquet",
        columns=["day", "blk2_M1", "M0"],
    )
    ok = fc.dropna(subset=["blk2_M1", "M0"])
    days = pd.to_datetime(ok["day"]).dt.normalize().drop_duplicates().sort_values()
    assert len(days) == int(ea.loc["blk2_M1", "n_days"]), (
        len(days),
        ea.loc["blk2_M1", "n_days"],
    )
    post = days[days >= pd.Timestamp("2016-01-01")]
    assert len(post) == int(eb.loc["blk2_M1", "n_days"]), (
        len(post),
        eb.loc["blk2_M1", "n_days"],
    )
    write_tab(
        "multihorizon",
        [
            src.relative_to(ROOT).as_posix()
            + " (the fixed variant: --through-close, FOMC panel of record)",
            "results/multihorizon/ttc_close_fomc1_forecasts.parquet (day ranges)",
        ],
        "lrrrrrr",
        [
            "construction",
            r"\shortstack{all days\\HAR OLS}",
            r"\shortstack{all days\\block ridge}",
            r"\shortstack{all days\\DM $t$}",
            r"\shortstack{from 2016\\HAR OLS}",
            r"\shortstack{from 2016\\block ridge}",
            r"\shortstack{from 2016\\DM $t$}",
        ],
        body,
    )
    macro("runappMhDays", fint(len(days)))
    macro("runappMhFirst", days.iloc[0].strftime("%Y-%m-%d"))
    macro("runappMhLast", days.iloc[-1].strftime("%Y-%m-%d"))
    macro("runappMhPostDays", fint(len(post)))
    macro("runappMhNaive", fnum(ea.loc["M0", "qlike"], 3))
    macro("runappMhAOne", fnum(ea.loc["a0_M1", "qlike"], 4))
    macro("runappMhBOne", fnum(ea.loc["blk2_M1", "qlike"], 4))
    macro("runappMhBThree", fnum(ea.loc["blk2_M3", "qlike"], 4))
    dms = p[p["forecast"].str.startswith("blk2")]["dm_blk2_vs_a0"]
    macro("runappMhDmLo", fnum(dms.abs().min(), 1))
    macro("runappMhDmHi", fnum(dms.abs().max(), 1))
    assert (dms < 0).all()
    bh = pd.read_csv(RES / "multihorizon" / "ttc_close_fomc1_byhour.csv")
    bh = bh[(bh["era"] == "all")].set_index(["hour", "forecast"])
    macro("runappMhFourteen", fnum(bh.loc[("14:00", "blk2_M1"), "qlike"], 3))
    macro("runappMhFourteenThirty", fnum(bh.loc[("14:30", "blk2_M1"), "qlike"], 3))
    # the plain variant's target omits the last bar (holdclose notebook, section 8d)
    txt = nb_output(NB_HC, "omits exactly the 15:30-16:00 bar")
    m = re.search(r"at 10:00 / 13:00 / 15:00: ([\d.]+)% / ([\d.]+)% / ([\d.]+)%", txt)
    assert m
    macro("runappMhMissTen", m.group(1))
    macro("runappMhMissFifteen", m.group(3))


# =========================================================================== sizing
def sizing() -> None:
    src = CL / "vrp_sized_rules.csv"
    v = pd.read_csv(src)
    sized = v[v["rule"] != "sign(s)"]
    body = []
    rules = [
        "(a) proportional s/rms",
        "(b) rank of |s|, sign kept",
        "(c) centred rank 2F(s)-1",
    ]
    lab = {
        "(a) proportional s/rms": r"(a) proportional, $s_d/\mathrm{rms}_d$",
        "(b) rank of |s|, sign kept": r"(b) rank of $|s_d|$, sign kept",
        "(c) centred rank 2F(s)-1": r"(c) centred rank, $2\hat F_d(s_d)-1$",
    }
    nf = v["forecast"].nunique()
    for block in ["after 252-day warm-up", "from the second day"]:
        for rule in rules:
            g = sized[(sized["rule"] == rule) & (sized["block"] == block)]
            assert len(g) == nf
            rr = g[g["forecast"] == RIDGE].iloc[0]
            body.append(
                row(
                    [
                        lab[rule],
                        block.replace(
                            "after 252-day warm-up", "after 252 days"
                        ).replace("from the second day", "from day 2"),
                        fint(rr["days"]),
                        fnum(rr["Sharpe mid"], 2),
                        f"{fnum(rr['dSharpe mid'], 2, plus=True)} {fci(rr['lo mid'], rr['hi mid'])}",
                        f"{int((g['dSharpe mid'] > 0).sum())} / {int((g['lo mid'] > 0).sum())} / {int((g['hi mid'] < 0).sum())}",
                        fnum(g["dSharpe mid"].median(), 2, plus=True),
                        f"{int((g['dSharpe crossed'] > 0).sum())} / {int((g['lo crossed'] > 0).sum())} / {int((g['hi crossed'] < 0).sum())}",
                    ]
                )
            )
        if block == "after 252-day warm-up":
            body.append(r"\midrule")
    write_tab(
        "sizing",
        [src.relative_to(ROOT).as_posix()],
        "llrrrrrr",
        [
            "size",
            "sample",
            "days",
            r"\shortstack{ridge\\Sharpe (mid)}",
            r"\shortstack{ridge: minus $\mathrm{sign}(s)$\\(mid) [95\%]}",
            r"\shortstack{" + str(nf) + r" forecasts (mid):\\$>0$ / CI$>0$ / CI$<0$}",
            r"\shortstack{median\\(mid)}",
            r"\shortstack{"
            + str(nf)
            + r" forecasts (crossed):\\$>0$ / CI$>0$ / CI$<0$}",
        ],
        body,
    )
    macro("runappSzForecasts", str(nf))
    assert (sized["lo mid"] <= 0).all() and (sized["lo crossed"] <= 0).all(), (
        "no sized rule has an interval above zero"
    )
    wa = sized[sized["block"] == "after 252-day warm-up"]
    a = wa[wa["rule"] == rules[0]]
    assert (a["dSharpe mid"] < 0).all()
    b = wa[wa["rule"] == rules[1]]
    macro("runappSzRankAbove", str(int((b["dSharpe mid"] > 0).sum())))
    macro("runappSzRankMed", fnum(b["dSharpe mid"].median(), 2, plus=True))
    c = wa[wa["rule"] == rules[2]]
    assert (c["dSharpe mid"] < 0).all()
    sg = v[
        (v["rule"] == "sign(s)")
        & (v["block"] == "after 252-day warm-up")
        & (v["forecast"] == RIDGE)
    ].iloc[0]
    macro("runappSzSignMid", fnum(sg["Sharpe mid"]))
    macro("runappSzDays", fint(sg["days"]))


# =========================================================================== portfolio + co-moves
def portfolio() -> None:
    src = CL / "portfolio_weights_causal.csv"
    w = pd.read_csv(src)
    body = []
    for _, r in w.iterrows():
        body.append(
            row(
                [
                    tex_escape(str(r["forecast"])).replace(
                        "fixed 1e-4", r"$\alpha=10^{-4}$"
                    ),
                    fnum(r["correlation with S&P, 15:30→close"], 2),
                    fnum(r["correlation with |S&P, 15:30→close|"], 2),
                    fnum(r["correlation with S&P, close-to-close"], 2),
                    fnum(r["mean risk share"], 2),
                    fnum(r["premium $ per $100 S&P (median)"], 2),
                    fnum(r["Sharpe combination"], 2),
                    f"{fnum(r['dSharpe'], 2, plus=True)} {fci(r['ci_lo'], r['ci_hi'])}",
                ]
            )
        )
    write_tab(
        "portfolio",
        [src.relative_to(ROOT).as_posix()],
        "lrrrrrrr",
        [
            "forecast",
            r"\shortstack{corr.\ S\&P\\15:30$\to$close}",
            r"\shortstack{corr.\ $|$S\&P$|$\\15:30$\to$close}",
            r"\shortstack{corr.\ S\&P\\close-to-close}",
            r"\shortstack{mean\\risk share}",
            r"\shortstack{premium \$\\per \$100 S\&P}",
            r"\shortstack{Sharpe\\combined}",
            r"\shortstack{minus S\&P alone\\{}[95\%]}",
        ],
        body,
    )
    r = w[w["forecast"] == RIDGE].iloc[0]
    macro("runappPwDays", fint(r["scored days"]))
    macro("runappPwFirst", str(r["first day"]))
    macro("runappPwSpx", fnum(r["Sharpe S&P alone"]))
    macro("runappPwComb", fnum(r["Sharpe combination"]))
    macro("runappPwGain", fnum(r["dSharpe"]))
    macro("runappPwGainCi", fci(r["ci_lo"], r["ci_hi"]))
    macro("runappPwShare", fnum(r["mean risk share"]))
    macro("runappPwDollar", fnum(r["premium $ per $100 S&P (median)"]))
    macro("runappPwCorrLo", fnum(w["correlation with S&P, close-to-close"].min()))
    macro(
        "runappPwCorrHi",
        fnum(w["correlation with S&P, close-to-close"].max(), plus=True),
    )
    macro("runappPwAbsLo", fnum(w["correlation with |S&P, 15:30→close|"].min()))
    macro("runappPwAbsHi", fnum(w["correlation with |S&P, 15:30→close|"].max()))
    macro("runappPwBestLo", fnum(w["ci_lo"].max()))
    assert (w["ci_lo"] < 0).all(), "every interval includes zero"
    macro("runappPwForecasts", str(len(w)))

    src_c = CL / "trade_return_comoves.csv"
    c = pd.read_csv(src_c)
    a, b = "block-diagonal ridge", "per-bar ridge (live-feasible set)"
    body = []
    for _, r in c.iterrows():
        body.append(
            row(
                [
                    tex_escape(str(r["series"]))
                    .replace("->", r"$\to$")
                    .replace("|", "$|$"),
                    fint(r["days"]),
                    f"{fnum(r[a + ': corr'], 3)} {fci(r[a + ': lo'], r[a + ': hi'], 3)}",
                    f"{fnum(r[b + ': corr'], 3)} {fci(r[b + ': lo'], r[b + ': hi'], 3)}",
                ]
            )
        )
    write_tab(
        "comoves",
        [src_c.relative_to(ROOT).as_posix()],
        "lrrr",
        [
            "same-day move",
            "days",
            "block-diagonal ridge [95\\%]",
            "per-bar ridge, live-feasible [95\\%]",
        ],
        body,
    )
    ex_a = int(((c[a + ": lo"] > 0) | (c[a + ": hi"] < 0)).sum())
    ex_b = int(((c[b + ": lo"] > 0) | (c[b + ": hi"] < 0)).sum())
    macro("runappCoExA", str(ex_a))
    macro("runappCoExB", str(ex_b))
    macro("runappCoSeries", str(len(c)))
    one = c[(c[a + ": lo"] > 0) | (c[a + ": hi"] < 0)].iloc[0]
    macro("runappCoOne", fnum(one[a + ": corr"], 2))
    macro("runappCoOneCi", fci(one[a + ": lo"], one[a + ": hi"], 3))


# =========================================================================== main
def main() -> None:
    GEN.mkdir(parents=True, exist_ok=True)
    repick()
    holdclose()
    perclock()
    restofday()
    post2024()
    decision()
    monthend()
    vixonly()
    perbar_pooled()
    multihorizon()
    sizing()
    portfolio()
    lines = [
        "% AUTO-GENERATED by writeup/make_appendix_running_tex.py -- do not edit.",
        "% Numbers quoted in the prose of writeup/sections/appendix_running.tex; each is",
        "% read from the source named at the table it belongs to (see the maker).",
    ]
    lines += [r"\newcommand{\%s}{%s}" % (k, v) for k, v in NUMS.items()]
    (GEN / "appendix_running_numbers.tex").write_text(
        "\n".join(lines) + "\n", encoding="utf-8", newline="\n"
    )
    trade = (GEN / "appendix_running_restofday_trade_numbers.tex").exists()
    print(
        f"wrote {len(WRITTEN)} tables and {len(NUMS)} number macros to "
        f"{GEN.relative_to(ROOT).as_posix()}; trading-test numbers: "
        + ("written" if trade else "absent (no trading_test_pooled.csv)")
    )
    assert len(set(WRITTEN)) == len(WRITTEN)


if __name__ == "__main__":
    main()
