"""Emit the FOMC-bucket QLIKE table from unification_fomc1_scores.csv.

Writes writeup/generated_fomc1/table_fomc_bucket.tex. Never hand-types
QLIKE or DM digits into the Data section; data_prep.tex \\input-s the
tabular.
"""

from __future__ import annotations

import os

import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "results", "unification_fomc1_scores.csv")
OUT_DIR = os.path.join(ROOT, "writeup", "generated_fomc1")
OUT = os.path.join(OUT_DIR, "table_fomc_bucket.tex")

# Display order and names for the Data-section table.
ARMS: list[tuple[str, str]] = [
    ("a0_ols_har", r"baseline (HAR + calendar OLS)"),
    ("a_bucket_fomc", r"FOMC calendar bucket (OLS)"),
    ("a_bucket_all_features", r"all features (OLS)"),
    ("b1_ridge", r"ridge (joint)"),
    ("b2_lasso", r"lasso"),
    ("blk2_user", r"block-diag ridge"),
]


def main() -> None:
    df = pd.read_csv(SRC)
    df = df.loc[~df["arm"].astype(str).str.contains("_condvar", regex=False)].copy()
    by_arm = df.set_index("arm")
    missing = [k for k, _ in ARMS if k not in by_arm.index]
    if missing:
        raise SystemExit(f"missing arms in {SRC}: {missing}")
    n_vals = {int(by_arm.loc[k, "n_bars"]) for k, _ in ARMS}
    if len(n_vals) != 1:
        raise SystemExit(f"n_bars not unique across arms: {sorted(n_vals)}")
    n = next(iter(n_vals))

    lines = [
        "% AUTO-GENERATED by writeup/make_fomc1_data_table.py --- do not edit.",
        f"% Source: results/unification_fomc1_scores.csv; n={n}; skip *_condvar.",
        r"\begin{tabular}{@{}lrr@{}}",
        r"\toprule",
        r"Arm & QLIKE & DM $t$ \\",
        r"\midrule",
    ]
    for key, label in ARMS:
        qlike = float(by_arm.loc[key, "qlike"])
        dm = float(by_arm.loc[key, "dm_t_vs_a0"])
        lines.append(f"{label} & {qlike:.5f} & ${dm:+.1f}$ \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", ""]

    os.makedirs(OUT_DIR, exist_ok=True)
    with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(lines))
    print("wrote", OUT)


if __name__ == "__main__":
    main()
