"""Standalone PDF for the 11:00 delta-hedged short.

Every day enters at 11:00, delta-hedge to close. Each forecast model
decides independently whether to buy the straddle back at 15:30 (its
own s>0) or hold to cash settlement. Never retypes a Sharpe.

Run:  python writeup/make_dh_causal_standalone_tex.py
"""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

ROOT = Path(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, str(ROOT / "notebooks"))
import atm_straddle_lib as asl  # noqa: E402

SRC = ROOT / "results" / "atm_straddle_intraday_holdclose" / "proposals" / "26"
GEN = ROOT / "writeup" / "generated_dh_causal"
WRITEUP = ROOT / "writeup"
FIG = SRC / "dh_causal_hists.png"

HOLD_LABEL = r"hold through cash-settle"
EXIT_HEADER = r"exit if $s>0$"
ENTRY = "11:00"
CLOSE = "15:30"

COLS = [
    ("n", "{:.0f}", r"$n$"),
    ("mean", "{:.3f}", r"mean"),
    ("std", "{:.3f}", r"std"),
    ("min", "{:.2f}", r"min"),
    ("max", "{:.2f}", r"max"),
    ("t_mean", "{:.2f}", r"$t$"),
    ("Sharpe_ann", "{:.2f}", r"Sharpe$_{\mathrm{ann}}$"),
    ("Sharpe_crossed", "{:.2f}", r"Sharpe$^{\times}_{\mathrm{ann}}$"),
    ("MaxDD", "{:.2f}", r"MaxDD"),
    ("MaxDD_crossed", "{:.2f}", r"MaxDD$^{\times}$"),
    ("n_exit", "{:.0f}", r"$n_{\mathrm{exit}}$"),
    ("pct_exit", "{:.1f}", r"\%exit"),
]

PREAMBLE = r"""
\documentclass{article}
\usepackage[T1]{fontenc}
\usepackage{lmodern}
\usepackage[landscape,margin=0.48in]{geometry}
\usepackage{booktabs}
\usepackage{amsmath}
\usepackage{graphicx}
\pagestyle{empty}
""".strip()


def _maxdd(x: pd.Series) -> float:
    """Worst peak-to-trough of the cumulative *sum* path, signed, in units of R.

    One unit a day, summed (not compounded), in expiration-date order; the
    running peak starts at zero, so a first-day loss already counts.
    """
    v = pd.Series(x).dropna().sort_index().to_numpy(float)
    if v.size < 1:
        return float("nan")
    path = np.cumsum(v)
    peak = np.maximum.accumulate(np.concatenate(([0.0], path)))[1:]
    return float((path - peak).min())


def _row(
    series: pd.Series,
    label: str,
    exit_flag: pd.Series | None = None,
    crossed: pd.Series | None = None,
) -> pd.DataFrame:
    s = series.dropna()
    size = pd.Series(-1.0, index=s.index)
    r = asl.rule_row(s, size=size)
    if exit_flag is None:
        r["n_exit"] = 0.0
        r["pct_exit"] = 0.0
    else:
        e = exit_flag.reindex(s.index).fillna(False).astype(bool)
        r["n_exit"] = float(e.sum())
        r["pct_exit"] = 100.0 * float(e.mean()) if len(e) else 0.0
    r["MaxDD"] = _maxdd(s)
    if crossed is None:
        r["Sharpe_crossed"] = float("nan")
        r["MaxDD_crossed"] = float("nan")
    else:
        xc = pd.Series(crossed).reindex(s.index).dropna()
        sd = float(xc.std(ddof=1)) if len(xc) >= 2 else float("nan")
        r["Sharpe_crossed"] = (
            float(xc.mean()) / sd * np.sqrt(asl.PERIODS_PER_YEAR)
            if (sd and sd > 0)
            else float("nan")
        )
        r["MaxDD_crossed"] = _maxdd(xc)
    return pd.DataFrame([r], index=[label])


def render_table(df: pd.DataFrame) -> str:
    ncol = 1 + len(COLS)
    lines = [
        "% AUTO-GENERATED by writeup/make_dh_causal_standalone_tex.py",
        r"\begingroup\small\setlength{\tabcolsep}{3.6pt}",
        r"\begin{tabular}{l" + "r" * len(COLS) + "}",
        r"\toprule",
        "& " + " & ".join(h for _, _, h in COLS) + r" \\",
        r"\midrule",
    ]
    header_done = False
    for name, row in df.iterrows():
        if name != HOLD_LABEL and not header_done:
            lines.append(r"\addlinespace")
            lines.append(rf"\multicolumn{{{ncol}}}{{l}}{{{EXIT_HEADER}}} \\")
            header_done = True
        prefix = r"\quad " if name != HOLD_LABEL else ""
        cells = [prefix + str(name)]
        for col, fmt, _ in COLS:
            v = float(row[col])
            # An undefined ratio (no down day, so the downside RMS is zero)
            # prints as an empty cell, never as "nan" or "inf".
            cells.append(fmt.format(v) if np.isfinite(v) else "")
        lines.append(" & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\endgroup"]
    return "\n".join(lines)


def _p26():
    import importlib.util

    path = ROOT / "writeup" / "intraday_proposals" / "26_causal_entry_flatten.py"
    spec = importlib.util.spec_from_file_location("p26_dh", path)
    mod = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    spec.loader.exec_module(mod)
    return mod


def _rule_mod():
    """The DH hold-to-close rule-table helpers (censored-IV re-inversion + Δ)."""
    if "--dh-holdclose" not in sys.argv:
        sys.argv.append("--dh-holdclose")
    sys.path.insert(0, str(ROOT / "writeup"))
    import make_rule_by_strategy_intraday_tex as m  # noqa: E402

    return m


def deck_frame(pkg: pd.DataFrame) -> tuple[pd.DataFrame, list[str]]:
    """The trade cache on the deck's days, with h_rem and the re-inverted hourly IV.

    Shared by hold_mark_1100 (the hedge tape and the 15:30 buy-back price) and
    by main (the 15:30 exit signal), so both read the SAME volatility: the raw
    vendor column is NaN on the censored bars, and a signal built from it is
    NaN there too, which silently turns "exit if s > 0" into "hold".
    """
    m = _rule_mod()
    deck = pd.read_parquet(m.DECK / "daily_blk2.parquet")
    days = pd.to_datetime(deck.index)
    p = pkg.copy()
    p["date"] = pd.to_datetime(p["date"])
    p = p[p["date"].isin(days)].copy()
    # The half-hour grid only: the 2026-09-18 chain's 09:35 opening stamp is off
    # it (its hours to the close are 6 h 25 min, not n_rem / 2), and the 11:00
    # series and its 15:30 exit never read it.
    p = p[p["hhmm"].str[3:].isin(["00", "30"])].copy()
    clocks = sorted(p["hhmm"].unique())
    if ENTRY not in clocks or CLOSE not in clocks:
        raise SystemExit(f"need {ENTRY} and {CLOSE} in {clocks}")
    n_rem = {c: len(clocks) - i for i, c in enumerate(clocks)}
    p["h_rem"] = p["hhmm"].map(n_rem).astype(float) * 0.5
    p["iv_hourly_used"] = m.iv_hourly_reinverted(p).to_numpy()
    return p, clocks


def hold_mark_1100(
    pkg: pd.DataFrame,
) -> tuple[pd.Series, pd.Series, pd.Series, pd.Series]:
    """Always-short DH from a fixed 11:00 entry: cash-settle vs 15:30 mark.

    Hold-through is the same tape as rule_by_strategy_dh_holdclose 11:00
    always-short: deck days, censored vendor IV re-inverted from the straddle
    mid, Δ rebalanced every 30 minutes, cash-settle at the official close.
    """
    p26 = _p26()
    m = _rule_mod()
    p, clocks = deck_frame(pkg)
    n_rem = {c: len(clocks) - i for i, c in enumerate(clocks)}
    j = clocks.index(ENTRY)
    j15 = clocks.index(CLOSE)
    dh = m.attach_long_dh(p)
    sl = (
        dh.loc[dh["hhmm"] == ENTRY]
        .dropna(subset=["entry", "exit", "K_c", "K_p", "S_close", "R"])
        .drop_duplicates("date")
        .set_index("date")
        .sort_index()
    )
    sl = sl.loc[sl["entry"].astype(float) > 0]
    dates = sl.index
    r_h = -sl["R"].astype(float)
    S_grid = p.pivot_table(
        index="date", columns="hhmm", values="S", aggfunc="first"
    ).reindex(index=dates, columns=clocks)
    IV_grid = p.pivot_table(
        index="date", columns="hhmm", values="iv_hourly_used", aggfunc="first"
    ).reindex(index=dates, columns=clocks)
    Kc = sl["K_c"].to_numpy(float)
    Kp = sl["K_p"].to_numpy(float)
    entry = sl["entry"].to_numpy(float)
    ex = sl["exit"].to_numpy(float)
    ST = sl["S_close"].to_numpy(float)
    Sg = S_grid.to_numpy(float)
    IVg = IV_grid.to_numpy(float)
    h_row = np.array([n_rem[c] * 0.5 for c in clocks])
    tot = np.where(IVg > 0, IVg * np.sqrt(h_row[None, :]), np.nan)
    tot[:, :j] = np.nan
    dlt = p26.pkg_delta(tot, Sg, Kc[:, None], Kp[:, None])
    nxt = np.full_like(Sg, np.nan)
    nxt[:, :-1] = Sg[:, 1:]
    nxt[:, -1] = ST
    dS = np.where(np.isfinite(Sg) & np.isfinite(nxt), nxt - Sg, 0.0)
    dS[:, :j] = 0.0
    tot15 = np.where(IVg[:, j15] > 0, IVg[:, j15] * np.sqrt(h_row[j15]), np.nan)
    mark = p26.pkg_price(tot15, Sg[:, j15], Kc, Kp)
    dS_f = dS.copy()
    dS_f[:, j15] = 0.0
    hedge_f = (dlt * dS_f).sum(axis=1)
    r_f = pd.Series((-(mark - entry) + hedge_f) / entry, index=dates)
    if "bid_entry" in sl.columns:
        bid = sl["bid_entry"].to_numpy(float)
    else:
        bid = sl["bid_c"].to_numpy(float) + sl["bid_p"].to_numpy(float)
    ok_bid = np.isfinite(bid) & (bid > 0)
    hedge_short = -sl["hedge_long"].to_numpy(float)
    r_h_x = pd.Series((-(ex - bid) + hedge_short) / entry, index=dates)
    r_f_x = pd.Series((-(mark - bid) + hedge_f) / entry, index=dates)
    r_h = r_h.where(np.isfinite(r_h))
    r_f = r_f.where(r_h.notna() & np.isfinite(r_f))
    r_h_x = r_h_x.where(r_h.notna() & ok_bid)
    r_f_x = r_f_x.where(r_f.notna() & ok_bid)
    return r_h, r_f, r_h_x, r_f_x


def main() -> None:
    hold = ROOT / "results" / "atm_straddle_intraday_holdclose"
    pkg = pd.read_parquet(sorted((hold / "cache").glob("trade_*.parquet"))[-1])
    r_hold, r_mark, r_hold_x, r_mark_x = hold_mark_1100(pkg)
    h = r_hold.dropna()
    hx = r_hold_x.dropna()
    sh = float(h.mean() / h.std(ddof=1) * np.sqrt(asl.PERIODS_PER_YEAR))
    shx = float(hx.mean() / hx.std(ddof=1) * np.sqrt(asl.PERIODS_PER_YEAR))
    print("11:00 hold n", int(h.size), "Sharpe_ann", sh, "Sharpe_crossed", shx)
    ref = pd.read_csv(
        ROOT
        / "results"
        / "atm_straddle_intraday_holdclose"
        / "rule_by_strategy_dh"
        / "1100"
        / "rule_by_strategy_always_short.csv",
        index_col=0,
    ).loc["all models"]
    assert int(h.size) == int(ref["n"]), (int(h.size), int(ref["n"]))
    assert abs(sh - float(ref["Sharpe_ann"])) < 1e-8, (sh, float(ref["Sharpe_ann"]))
    assert abs(shx - float(ref["Sharpe_crossed"])) < 1e-6, (
        shx,
        float(ref["Sharpe_crossed"]),
    )
    print("GATE 11:00 always-short matches rule_by_strategy_dh_holdclose_1100")
    # The exit signal's implied slice uses the RE-INVERTED hourly IV, the same
    # volatility the 15:30 buy-back price is computed from. The raw vendor
    # column is NaN on the censored 15:30 bars (five, all in March 2020), and a
    # NaN signal made every model silently hold on exactly those days.
    frame15, _ = deck_frame(pkg)
    iv15 = (
        frame15.loc[frame15["hhmm"] == CLOSE, ["date", "iv_hourly_used"]]
        .drop_duplicates("date")
        .set_index("date")["iv_hourly_used"]
        .astype(float)
    )
    assert bool(np.isfinite(iv15.reindex(h.index)).all()), (
        "a scored day has no 15:30 implied slice for the exit signal"
    )
    slice15 = iv15**2 * 0.5

    parts = [_row(r_hold, HOLD_LABEL, crossed=r_hold_x)]
    r_exit = r_hold
    for tag in asl.MODEL_ORDER:
        pan = asl.load_yhat_panel(asl.yhat_paths(ROOT)[tag])
        y15 = pan[["t", "rv_hat"]].copy()
        y15["t"] = pd.to_datetime(y15["t"], utc=True) - pd.Timedelta(minutes=30)
        y15["date"] = (
            pd.to_datetime(y15["t"])
            .dt.tz_convert("America/New_York")
            .dt.normalize()
            .dt.tz_localize(None)
        )
        # 15:30 ET = 20:00 or 19:00 UTC; bar-end label is 16:00. After -30min the stamp is 15:30.
        et = pd.to_datetime(y15["t"], utc=True).dt.tz_convert("America/New_York")
        y15 = y15[et.dt.strftime("%H:%M") == "15:30"]
        s = y15.groupby("date")["rv_hat"].mean() - slice15
        s = s.reindex(r_hold.index)
        exit_flag = s > 0
        r = pd.Series(
            np.where(exit_flag.fillna(False), r_mark, r_hold), index=r_hold.index
        )
        r = r.where(r_hold.notna())
        rx = pd.Series(
            np.where(exit_flag.fillna(False), r_mark_x, r_hold_x), index=r_hold.index
        )
        rx = rx.where(r_hold.notna())
        label = asl.YHAT_LABEL[tag].replace("&", r"\&")
        parts.append(_row(r, label, exit_flag, crossed=rx))
        if tag == "blk2":
            r_exit = r

    tab = pd.concat(parts)
    GEN.mkdir(parents=True, exist_ok=True)
    (GEN / "table_dh_causal.tex").write_text(render_table(tab) + "\n", encoding="utf-8")

    x = r_exit.dropna()
    fig, ax = plt.subplots(figsize=(8.4, 2.35))
    ax.hist(x, bins=40, color="0.35", edgecolor="white")
    ax.axvline(0, color="k", lw=0.6)
    ax.set_xlabel("daily return (per unit of premium)")
    ax.set_ylabel("days")
    ax.set_title(
        f"Delta-hedged 11:00 short, exit if the 15:30 signal is positive ({len(x)} days)"
    )
    fig.tight_layout()
    fig.savefig(FIG, dpi=140, bbox_inches="tight")
    plt.close(fig)
    fig_rel = os.path.relpath(FIG, WRITEUP).replace("\\", "/")

    body = "\n".join(
        [
            "% AUTO-GENERATED by writeup/make_dh_causal_standalone_tex.py",
            "% Build: pdflatex -interaction=nonstopmode dh_causal_standalone.tex",
            PREAMBLE,
            r"\begin{document}",
            r"\begin{center}",
            r"{\large\bfseries 0DTE delta-hedged ATM straddles, 11:00 entry held till close/\mbox{15:30}}\\[0.5ex]",
            r"\small Every day sells the nearest-OTM straddle at 11:00 and delta-hedges to 16:00. "
            r"At 15:30 each forecast model decides on its own whether to buy the straddle back: "
            r"exit the short if \emph{that} model's $s>0$ "
            r"(its realized variance forecast above implied); otherwise cash-settle.",
            r"\\[0.9ex]",
            r"\input{generated_dh_causal/table_dh_causal}",
            r"\end{center}",
            r"\vspace{0.7em}",
            r"\noindent\small\textbf{Delta hedge.} "
            r"(1)~Sell the nearest-OTM call and put at 11:00; those strikes stay unchanged. "
            r"(2)~Every later 30-minute stamp until 15:30, read the vendor spot and vendor hourly IV at that stamp. "
            r"Total vol is that IV times the square root of hours remaining to 16:00. "
            r"Straddle delta is Black--76 call delta plus put delta (interest rate zero, forward = spot). "
            r"Because the straddle is short, hold plus-delta of the index. "
            r"Stock P\&L over the next half hour is delta times the spot change. "
            r"(3)~At 15:30, if \emph{that row's} model has $s>0$, buy the straddle back at the Black--76 mark and close the stock. "
            r"If not, cash-settle versus the GSPC close (last stock step uses that close versus the 15:30 spot). "
            r"No look-ahead: the entry uses only the 11:00 quote; each rebalance uses only the quote at that stamp.",
            r"\vspace{0.35em}",
            r"\begin{center}",
            r"\includegraphics[width=0.76\textwidth]{%s}\\[0.25ex]" % fig_rel,
            r"\small Daily return of the 11:00 short; 15:30 exit uses the block-diagonal ridge $s$.",
            r"\end{center}",
            r"\par\vspace{0.35em}",
            r"\noindent\small One expiration day is one return. "
            r"\mbox{Sharpe$_{\mathrm{ann}}=(\mathrm{mean}/\mathrm{std})\times\sqrt{252}$}. "
            r"$t$-stat is $\sqrt{n}\cdot\mathrm{mean}/\mathrm{std}$. "
            r"Every day enters at 11:00. "
            r"Each model only decides whether to exit at 15:30. "
            r"$n_{\mathrm{exit}}$ is days that model buys the straddle back. "
            r"Sharpe$^{\times}_{\mathrm{ann}}$ is the same book at the crossed spread: "
            r"sell the 11:00 straddle at the bid, then cash-settle or buy back at the 15:30 mark; "
            r"P\&L is still divided by the midpoint premium. "
            r"MaxDD is the worst peak-to-trough decline of the cumulative sum of the daily "
            r"returns, in date order, one unit a day (summed, not compounded), signed and in "
            r"units of entry premium like min; MaxDD$^{\times}$ is the same at the crossed spread.",
            r"\end{document}",
            "",
        ]
    )
    tex = WRITEUP / "dh_causal_standalone.tex"
    tex.write_text(body, encoding="utf-8")
    log = WRITEUP / "dh_causal_standalone.log"
    with open(log, "w", encoding="utf-8") as fh:
        subprocess.check_call(
            ["pdflatex", "-interaction=nonstopmode", tex.name],
            cwd=str(WRITEUP),
            stdout=fh,
        )
    pdf = WRITEUP / "dh_causal_standalone.pdf"
    print("wrote", pdf)


if __name__ == "__main__":
    main()
