"""Emit the full spectral+causal-tune battery table as compilable LaTeX.

Reads writeup/metrics_table_causal_tune_plus_spectral.csv (built by
build_extended_battery.py) and writes a standalone .tex holding every arm,
ranked by QLIKE, with the spectral-kNN family marked so a reader can see at a
glance where it lands against the audited causal-tuned arms.
"""
import pathlib

import pandas as pd

SRC = pathlib.Path("writeup/metrics_table_causal_tune_plus_spectral.csv")
OUT = pathlib.Path("writeup/causal_tune_plus_spectral_standalone.tex")

df = pd.read_csv(SRC).sort_values("qlike").reset_index(drop=True)
inc = float(df.incumbent_qlike.dropna().iloc[0])
best_q = df.qlike.min()
best_r2 = df.oos_r2.max()

# `baseline` is the empty-exog SUBGROUPS key, but the word collides with the
# incumbent row and reads as "the comparator". Display it unambiguously; the
# underlying key is unchanged in the CSV and stated in the caption.
BUCKET_DISPLAY = {"baseline": "no-exog (HAR only)"}

# Incumbent metrics taken VERBATIM from the audited table
# (writeup/causal_tune_battery_table.tex final row) -- not recomputed here, so
# the extended table cannot drift from the signed artifact.
INCUMBENT_ROW = dict(mae=1.283e-6, mse=4.336e-11, mz_beta=0.929, mz_r2=0.6984)

NICE = {
    "lgbm": "LightGBM causal-tuned", "xgb": "XGBoost causal-tuned",
    "ridge": "ridge causal-tuned", "reclasso": "Lasso causal-tuned",
    "reclasticnet": "ElasticNet causal-tuned",
}


def esc(s):
    return str(s).replace("_", r"\_")


def bucket_label(b):
    return esc(BUCKET_DISPLAY.get(str(b), str(b)))


def sci(x, digits=3):
    try:
        v = float(x)
    except (TypeError, ValueError):
        return "--"
    if v == 0:
        return "0"
    s = f"{v:.{digits}e}"
    m, e = s.split("e")
    return f"${m} \\times 10^{{{int(e)}}}$"


rows = []
crossed = False
for r in df.itertuples():
    # light dotted rule at the point where arms stop beating the incumbent:
    # everything above it has QLIKE < the comparator, everything below is worse
    if not crossed and r.qlike > inc:
        rows.append(r"\hdashline")
        crossed = True
    spectral = r.family == "spectral-kNN"
    est = NICE.get(str(r.estimator), str(r.estimator))
    est = esc(est)
    if spectral:
        est = r"\textit{" + est + "}"
    q = f"{r.qlike:.5f}"
    if abs(r.qlike - best_q) < 1e-12:
        q = r"\textbf{" + q + "}"
    o = f"{r.oos_r2:.4f}"
    if abs(r.oos_r2 - best_r2) < 1e-12:
        o = r"\textbf{" + o + "}"
    dm = f"${r.dm:.1f}$, {sci(r.dm_p, 1)}"
    rows.append(
        f"{bucket_label(r.bucket)} & {est} & {q} & {sci(r.mae)} & {sci(r.mse)} & "
        f"{o} & {r.mz_beta:.3f} & {r.mz_r2:.4f} & {dm} \\\\"
    )

n_sp = int((df.family == "spectral-kNN").sum())
n_beat = int(((df.family == "spectral-kNN") & (df.dm_better == "a")).sum())
sp_rank = int(df.index[df.family == "spectral-kNN"][0]) + 1

caption = (
    r"Causal hyperparameter-tuning battery extended with the spectral-kNN "
    r"analog family (\textit{italic} rows). All arms share one out-of-sample "
    r"panel ($n = 218{,}934$ thirty-minute bars, 100 walk-forward chunks with a "
    r"24{,}000-bar warm-up halo, pooled per bar) and one comparator: OLS on "
    r"HAR $+$ calendar with no exogenous features (the production ridge path at "
    r"$\alpha = 0$, exact OLS, per-bar refit), QLIKE $= " + f"{inc:.5f}" + r"$. "
    r"OOS-$R^2$ is measured against that incumbent, so $>0$ means the arm beats "
    r"it. DM is a Diebold--Mariano test on per-bar QLIKE loss with HAC standard "
    r"errors; negative $t$ favours the arm. The spectral-kNN arms compose a "
    r"residualizer (identity, or OLS with the per-window identifiability mask) "
    r"with a $W$-bar view of the target path concatenated to the bucket's "
    r"non-target-derived feature row, matched by Gaussian-weighted $k$NN either "
    r"directly (passthrough) or after a $d$-dimensional Laplacian embedding. "
    r"Best QLIKE and best OOS-$R^2$ in bold. The dotted rule marks where arms stop beating the incumbent: every row above it has QLIKE below "
    + f"{inc:.5f}" + r", every row below is worse. "
    + f"Of {n_sp} spectral arms, {n_beat} beat the incumbent; the best ranks "
      f"{sp_rank} of {len(df)}. "
    + r"The empty-exog bucket (SUBGROUPS key \texttt{baseline}) is displayed as "
      r"\emph{no-exog (HAR only)} so it is not confused with the incumbent row; "
      r"the underlying key is unchanged in the CSV. "
    + r"\textbf{Provenance:} the causal-tuned arms are audit-signed; the "
      r"spectral-kNN arms are NOT --- they were run from an unsigned spec "
      r"outside the submission journal, and cells whose unpenalized design "
      r"went singular ($\mathrm{MZ}\text{-}\beta < 0.1$) are excluded."
)

doc = (
    "% Auto-generated by writeup/make_spectral_table.py -- do not hand-edit.\n"
    "\\documentclass{article}\n"
    "\\usepackage[paperwidth=13in,paperheight=20in,margin=0.5in]{geometry}\n"
    "\\usepackage{booktabs}\n\\usepackage{amsmath}\n\\usepackage{amssymb}\n"
    # arydshln loaded AFTER booktabs; supplies \hdashline for the incumbent
    # marker. Short dash + wide gap reads as a light dotted rule.
    "\\usepackage{arydshln}\n"
    "\\setlength\\dashlinedash{0.5pt}\n\\setlength\\dashlinegap{2.5pt}\n"
    "\\setlength\\arrayrulewidth{0.4pt}\n"
    "\\pagestyle{empty}\n\\begin{document}\n"
    "\\begin{table}[t]\n\\centering\n\\caption{" + caption + "}\n"
    "\\vspace{4pt}\n\\footnotesize\n\\setlength{\\tabcolsep}{4pt}\n"
    "\\begin{tabular}{@{}llccccccc@{}}\n\\toprule\n"
    "exogenous bucket & estimator & QLIKE & MAE & MSE & OOS-$R^2$ & "
    "MZ-$\\beta$ & MZ-$R^2$ & DM vs.\\ incumbent ($t$, $p$) \\\\\n\\midrule\n"
    + "\n".join(rows)
    + "\n\\midrule\n"
    # the comparator every DM column is measured against; its own OOS-R^2 is
    # undefined (it IS the benchmark). Values quoted verbatim from the audited
    # table so the extended one cannot drift from the signed artifact.
    + "\\emph{OLS-on-HAR incumbent} & none (OLS) & "
    + f"{inc:.5f}" + " & " + sci(INCUMBENT_ROW["mae"]) + " & "
    + sci(INCUMBENT_ROW["mse"]) + " & --- & "
    + f"{INCUMBENT_ROW['mz_beta']:.3f}" + " & "
    + f"{INCUMBENT_ROW['mz_r2']:.4f}" + " & (comparator) \\\\\n"
    + "\\bottomrule\n\\end{tabular}\n\\end{table}\n\\end{document}\n"
)

with open(OUT, "w", encoding="utf-8", newline="\n") as fh:
    fh.write(doc)
print(f"wrote {OUT} ({len(df)} arms, {n_sp} spectral)")
